{
 "title": "KubeDB / Neo4j / Pod",
 "time": { "from": "2025-12-19T03:03:57.798Z", "to": "2025-12-19T04:40:09.227Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Neo4j",
    "query": {
     "query": "label_values(kubedb_com_neo4j_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(neo4j_dbms_vm_threads{namespace=~\"$namespace\",pod=~\"${app}-.*\"},pod)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "{__name__=~\"neo4j_database_.*_store_size_database\"}"
    }
   },
   {
    "name": "leader",
    "query": {
     "query": "query_result(neo4j_database_${database}_cluster_raft_is_leader{namespace=~\"$namespace\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Neo4j", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\"$pod\",phase=~\"Running\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(max_over_time(container_start_time_seconds{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_dbms_bolt_connections_running{pod=~\"$pod\",namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "CPU And Memory Usage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",namespace=~\"$namespace\"})",
     "legendFormat": "used memory"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",namespace=~\"$namespace\"}[5m])) / count(node_cpu_seconds_total{mode=\"system\"}) * 100",
     "legendFormat": "CPU used (%)"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last Committed Write Transaction ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_database_${database}_transaction_last_committed_tx_id_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Last Closed Write Transaction ID"
    }
   ]
  },
  {
   "title": "Committed Transaction Speed",
   "type": "stat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(neo4j_database_${database}_transaction_committed_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Property creation speed (ids)",
   "type": "stat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(neo4j_database_${database}_ids_in_use_property{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Rolled back Transaction Speed",
   "type": "stat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(neo4j_database_${database}_transaction_rollbacks_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Committed Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_database_${database}_transaction_committed_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "rate {{instance}}"
    },
    {
     "expr": "irate(neo4j_database_${database}_transaction_committed_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "iRate {{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "All transaction metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_database_${database}_transaction_(committed|rollbacks)_total\", pod=~\"$pod\",namespace=~\"$namespace\"}, \"label\", \"$1\", \"__name__\", \".*transaction_(committed|rollbacks)_total\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Committed Read Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_database_${database}_transaction_committed_read_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Committed Write Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_database_${database}_transaction_committed_write_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_database_${database}_transaction_committed_total{pod =~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Total Committed Tr.s {{instance}}"
    },
    {
     "expr": "neo4j_database_${database}_transaction_committed_read_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Committed Read Tr.s {{instance}}"
    },
    {
     "expr": "neo4j_database_${database}_transaction_committed_write_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Committed Write Tr.s {{instance}}"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_database_${database}_transaction_active_read{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Active read {{instance}}"
    },
    {
     "expr": "neo4j_database_${database}_transaction_active_write{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Active write {{instance}}"
    },
    {
     "expr": "neo4j_database_${database}_transaction_peak_concurrent_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Peak concurrent {{instance}}"
    }
   ]
  },
  { "title": "Page Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Page cache faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_page_faults_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache faults/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_page_faults_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hit Ratio",
   "type": "gauge",
   "description": "The ratio of hits to the total number of lookups in the page cache",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_hit_ratio{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits Rate (hits/sec)",
   "type": "timeseries",
   "description": "Per-second Neo4j Page Cache Hits",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_hits_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits",
   "type": "timeseries",
   "description": "The total number of page hits happened in the page cache",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_hits_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "description": "Neo4j Checkpoints. \nCheckpointing is the process of flushing all pending page updates from the page cache to the store files",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_database_${database}_check_point_(events|total_time)_total\", pod=~\"$pod\",namespace=~\"$namespace\"}, \"label\", \"$1\", \"__name__\", \".*check_point_(events|total_time)_total\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint event duration sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "neo4j_database_${database}_check_point_duration{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Bolt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Bolt Messages Queue",
   "type": "timeseries",
   "description": "Messages received - Messages started",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_dbms_bolt_messages_received_total{pod=~\"$pod\",namespace=~\"$namespace\"} - neo4j_dbms_bolt_messages_started_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Bolt Msg Queue Length {{instance}}"
    },
    {
     "expr": "label_replace({__name__=~\"neo4j_dbms_bolt_messages_(received|started)_total\", pod=~\"$pod\",namespace=~\"$namespace\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dbms_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    },
    {
     "expr": "rate(neo4j_dbms_bolt_messages_received_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "Bolt msg received rate {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dbms_bolt_connections_.+\", pod=~\"$pod\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dbms_bolt_connections_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "JVM Heap Size",
   "type": "timeseries",
   "description": "Heap memory (eden space, old generation, survivor space)\nNon-heap memory (metaspace, compressed class space, code cache)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"neo4j_dbms_vm_memory_pool_g1_(eden|old|survivor).*\", pod=~\"$pod\",namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}} heap"
    }
   ]
  },
  {
   "title": "VM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_dbms_vm_threads{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "vm live threads {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Used Buffer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "neo4j_dbms_vm_memory_buffer_direct_used{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "memory buffer direct used {{instance}}"
    },
    {
     "expr": "neo4j_dbms_vm_memory_buffer_mapped_used{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "memory buffer mapped used{{instance}}"
    }
   ]
  },
  {
   "title": "VM Garbage Collector",
   "type": "timeseries",
   "description": "Time and counters",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"neo4j_dbms_vm_gc_time_g1_.+_generation_total\", pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    },
    {
     "expr": "delta(neo4j_dbms_vm_gc_time_g1_old_generation_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "delta g1 old g total {{instance}}"
    },
    {
     "expr": "delta(neo4j_dbms_vm_gc_time_g1_young_generation_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "delta g1 young g total {{instance}}"
    }
   ]
  },
  { "title": "Cypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Cypher replan events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "neo4j_database_${database}_cypher_replan_events_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  }
 ]
}