{
 "title": "KubeDB / ClickHouse / Database",
 "tags": [
  "database",
  "clickhouse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "ClickHouse",
    "query": {
     "query": "label_values(kubedb_com_clickhouse_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Service Uptime",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Healthy Pods Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"} > 0)"
      }
     ]
    },
    {
     "title": "Cluster Status",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\",job=~\"$app+-stats\"} == 1"
      }
     ]
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseMetrics_Query{namespace=~\"$namespace\", service=~\"$app+-stats\"}[5m])\n)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Active ClickHouse Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ClickHouseMetrics_TCPConnection{namespace=~\"$namespace\",service=~\"$app+-stats\"})\n",
       "legendFormat": "TCP Connection - {{pod}}"
      }
     ]
    },
    {
     "title": "ClickHouse Metrics reads vs writes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ClickHouseMetrics_Read{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "reads - {{ pod }}"
      },
      {
       "expr": "rate(ClickHouseMetrics_Write{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "write - {{ pod }}"
      }
     ]
    },
    {
     "title": "ClickHouse network received vs sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ClickHouseMetrics_NetworkReceive{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "received - {{ pod }}"
      },
      {
       "expr": "rate(ClickHouseMetrics_NetworkSend{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "sent - {{ pod }}"
      }
     ]
    },
    {
     "title": "Top 5 Pods by Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5, avg by (pod, query_type) (\n  increase(ClickHouseProfileEvents_Query{namespace=~\"$namespace\",service=~\"$app+-stats\"}[1h]) > 0\n))",
       "legendFormat": "{{ pod }} "
      }
     ]
    },
    {
     "title": "ClickHouse Opened File Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_OpenedFileCacheHits{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "ClickHouse File Cache Miss Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_OpenedFileCacheMisses{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Parts Per Partition",
     "type": "stat",
     "description": "Maximum number of parts per partition over the specified period of time.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ClickHouseAsyncMetrics_MaxPartCountForPartition{namespace=~\"$namespace\",service=~\"$app+-stats\"})\n"
      }
     ]
    },
    {
     "title": "Percent of Failed SELECTs",
     "type": "stat",
     "description": "Percentage of the failed SELECTs over the specified period of time.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_FailedSelectQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[$__rate_interval])\n)\n/\nsum(\n  rate(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[$__rate_interval])\n) * 100\n\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Percent of Failed INSERTs",
     "type": "stat",
     "description": "Percentage of the failed INSERTs over the specified period of time (both synchronous and asynchronous).",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(rate(ClickHouseProfileEvents_FailedInsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h]))\n  +\n  sum(rate(ClickHouseProfileEvents_FailedAsyncInsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h]))\n)\n/\n(\n  sum(rate(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h]))\n  +\n  sum(rate(ClickHouseProfileEvents_AsyncInsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h]))\n) * 100\n\n\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "logged errors",
     "type": "stat",
     "description": "Number of log message with ERROR (and higher) severity over the specified period of time.asynchronous).",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  increase(ClickHouseProfileEvents_LogError{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ClickHouse Cluster Query Rate",
     "type": "stat",
     "description": "Shows the total queries per second executed by all ClickHouse pods",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_Query{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n"
      }
     ]
    },
    {
     "title": "Queries with MEMORY_LIMIT_EXCEEDED",
     "type": "stat",
     "description": "Number of times when memory limit exceeded for query.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n"
      }
     ]
    },
    {
     "title": "Failed Queries",
     "type": "stat",
     "description": "Number of failed queries.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_FailedQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n"
      }
     ]
    },
    {
     "title": "SELECT Queries",
     "type": "stat",
     "description": "Same as Queries, but only for SELECT queries.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n"
      }
     ]
    },
    {
     "title": "Failed SELECT Queries",
     "type": "stat",
     "description": "Same as Failed Queries, but only for SELECT queries.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_FailedSelectQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n\n"
      }
     ]
    },
    {
     "title": "Synchronous INSERT Queries",
     "type": "stat",
     "description": "Same as Queries, but only for INSERT queries. Only accounts for synchronous inserts.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n\n"
      }
     ]
    },
    {
     "title": "Asynchronous INSERT Queries",
     "type": "stat",
     "description": "Same as Queries, but only for INSERT queries. Only accounts for asynchronous inserts.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_AsyncInsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n\n"
      }
     ]
    },
    {
     "title": "Failed Asynchronous INSERT Queries",
     "type": "stat",
     "description": "Same as Failed Queries, but only for INSERT queries. Only accounts for asynchronous inserts.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  rate(ClickHouseProfileEvents_FailedAsyncInsertQuery{namespace=~\"$namespace\", service=~\"$app+-stats\"}[1h])\n)\n\n\n\n"
      }
     ]
    }
   ]
  }
 ]
}