{
 "title": "milvus",
 "tags": [ "milvus2.0" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance / Release",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, instance)"
    }
   },
   {
    "name": "collection_name",
    "label": "collection_name",
    "query": {
     "query": "label_values(milvus_proxy_req_count{namespace=\"$namespace\"},collection_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"PetSet\",},pod)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "node_id",
    "label": "node_id",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},node_id)"
    }
   },
   {
    "name": "cache_name",
    "label": "cache_name",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},cache_name)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search Vector Count Rate",
   "type": "graph",
   "description": "per-second increasing rate of searching vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_search_vectors_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Insert Vector Count Rate",
   "type": "graph",
   "description": "per-second increasing rate of inserting vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_insert_vectors_count{namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_proxy_sq_latency_bucket{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{query_type}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type) / sum(increase(milvus_proxy_sq_latency_count{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type)"
    }
   ]
  },
  {
   "title": "Collection Search Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search request for a specified collection over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_proxy_collection_sq_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{query_type}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_collection_sq_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type) / sum(increase(milvus_proxy_collection_sq_latency_count{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type)"
    }
   ]
  },
  {
   "title": "Mutation Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of mutation request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, msg_type, pod, node_id) (rate(milvus_proxy_mutation_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{msg_type}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_mutation_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, msg_type) / sum(increase(milvus_proxy_mutation_latency_count{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, msg_type)"
    }
   ]
  },
  {
   "title": "Collection Mutation Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of mutation request for a specified collection over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, msg_type, pod, node_id) (rate(milvus_proxy_collection_mutation_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{msg_type}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_collection_mutation_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, msg_type) / sum(increase(milvus_proxy_collection_mutation_latency_count{instance=~\"$instance\", namespace=\"$namespace\", collection_name=~\"$collection_name\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, msg_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{msg_type}}"
    }
   ]
  },
  {
   "title": "Wait Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of wait search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_proxy_sq_wait_result_latency_bucket{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_wait_result_latency_sum{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type) / sum(increase(milvus_proxy_sq_wait_result_latency_count{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Reduce Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of reduce search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_proxy_sq_decode_result_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_reduce_result_latency_sum{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type) / sum(increase(milvus_proxy_sq_reduce_result_latency_count{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Decode Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of decode search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_sq_decode_result_latency_sum{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type) / sum(increase(milvus_proxy_sq_decode_result_latency_count{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])) by (pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_proxy_sq_decode_result_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\",container=\"$container\",job=\"$job\"}[2m])))"
    }
   ]
  },
  {
   "title": "Cache Update Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of update cache over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_cache_update_latency_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_cache_update_latency_sum{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_cache_update_latency_count{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Success Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of success requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_req_count{instance=~\"$instance\",namespace=\"$namespace\", status=\"success\"}[2m])/120) by(function_name, pod, node_id)",
     "legendFormat": "{{function_name}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Cache Hit rate",
   "type": "graph",
   "description": "Average cache hits per minute of cache operations.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_cache_hit_count{namespace=\"$namespace\",cache_name=\"$cache_name\", cache_state=\"hit\"}[2m])) \n  by(cache_name, pod, node_id)\n/\nsum(increase(milvus_proxy_cache_hit_count{namespace=\"$namespace\", cache_name=\"$cache_name\",cache_state=\"hit\"}[2m])) \n  by(cache_name, pod, node_id)"
    }
   ]
  },
  {
   "title": "Apply Timestamp Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of apply timestamp over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_apply_timestamp_latency_bucket{instance=~\"$instance\",namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_apply_timestamp_latency_sum{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_apply_timestamp_latency_count{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Received Byte Rate",
   "type": "graph",
   "description": "per-second increasing rate of bytes received  in proxy",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_receive_bytes_count{namespace=\"$namespace\",job=\"$job\"}[2m])/120) by(pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Apply PK Latency",
   "type": "graph",
   "description": "The 99th percentile of latency for applying PK over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_apply_pk_latency_bucket{instance=~\"$instance\", namespace=\"$namespace\", job=\"$job\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_apply_pk_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", job=\"$job\"}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_apply_pk_latency_count{instance=~\"$instance\", namespace=\"$namespace\", job=\"$job\"}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_req_latency_sum{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_req_latency_count{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{function_name}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Faild Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of faild requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(milvus_proxy_req_count{namespace=\"kubedb\",collection_name=\"health_check_test\", status=\"fail\"}[5m]) "
    }
   ]
  },
  {
   "title": "Send Byte Rate",
   "type": "graph",
   "description": "per-second increasing rate of bytes sent back to the client by the Proxy in response to a Search or Query request.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_send_bytes_count{namespace=\"$namespace\",job=\"$job\"}[2m])/120) by(pod, node_id)"
    }
   ]
  },
  { "title": "Root Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Proxy Node Num",
   "type": "graph",
   "description": "Number of proxy nodes which has register with etcd",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_proxy_num{instance=~\"$instance\", namespace=\"$namespace\",container=\"$container\",job=\"$job\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Timestamp Saved",
   "type": "graph",
   "description": "RootCoord stores pre-assigned timestamps in the metastore",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "milvus_rootcoord_timestamp_saved{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "tiestamp"
    }
   ]
  },
  {
   "title": "Produced Timetick Time Taken",
   "type": "graph",
   "description": "The 99th percentile and average latency for rootcoord to finish synchronizing timestamp messages to all pchanels.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(milvus_rootcoord_sync_timetick_latency_sum{instance=~\"$instance\", namespace=\"$namespace\", job=\"$job\", container=~\"$container\"}[2m])\n)\n/\nsum(\n  increase(milvus_rootcoord_sync_timetick_latency_count{instance=~\"$instance\", namespace=\"$namespace\", job=\"$job\", container=~\"$container\"}[2m])\n)",
     "legendFormat": "avg-latency"
    }
   ]
  },
  {
   "title": "DDL Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of DDL request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, function_name) (rate(milvus_rootcoord_ddl_req_latency_bucket{instance=~\"$instance\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{function_name}}"
    },
    {
     "expr": "sum(increase(milvus_rootcoord_ddl_req_latency_sum{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (function_name) / sum(increase(milvus_rootcoord_ddl_req_latency_count{instance=~\"$instance\", namespace=\"$namespace\"}[2m])) by (function_name)",
     "legendFormat": "avg-{{function_name}}"
    }
   ]
  },
  {
   "title": "DML Channel Num",
   "type": "graph",
   "description": "The number of DML channels",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_dml_channel_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "DDL Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of DDL request",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_rootcoord_ddl_req_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status, function_name)",
     "legendFormat": "{{function_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "graph",
   "description": "RoootCoord current latest timestamp",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "milvus_rootcoord_timestamp{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "tiestamp"
    }
   ]
  },
  {
   "title": "Msgstream Num",
   "type": "graph",
   "description": "The number of Msgstream objects.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_msgstream_obj_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "ID Alloc Rate",
   "type": "graph",
   "description": "per-second increasing rate of IDs assigned by RootCoord",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_rootcoord_id_alloc_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Partition Num",
   "type": "graph",
   "description": "The number of partitions.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_partition_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Credential Num",
   "type": "graph",
   "description": "The number of credential",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_credential_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Collection Num",
   "type": "graph",
   "description": "The number of collections.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_collection_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  { "title": "Query Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Collection Loaded Num",
   "type": "graph",
   "description": "Total number of loaded collections.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querycoord_collection_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Load Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of load request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_load_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-latency"
    },
    {
     "expr": "sum(increase(milvus_querycoord_load_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) / sum(increase(milvus_querycoord_load_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m]))",
     "legendFormat": "avg-latency"
    }
   ]
  },
  {
   "title": "Load Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of load requests.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querycoord_load_req_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Release Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of relaase requests.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querycoord_release_req_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Load Task",
   "type": "graph",
   "description": "Total number pf loading task.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querycoord_task_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Release Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of release request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_release_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-latency"
    },
    {
     "expr": "sum(increase(milvus_querycoord_release_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) / sum(increase(milvus_querycoord_release_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m]))",
     "legendFormat": "avg-latency"
    }
   ]
  },
  {
   "title": "Query Node Num",
   "type": "graph",
   "description": "Number of Query nodes which has register with etcd.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querycoord_querynode_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Task Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of task request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_task_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-latency"
    },
    {
     "expr": "sum(increase(milvus_querycoord_task_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) / sum(increase(milvus_querycoord_task_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m]))",
     "legendFormat": "avg-latency"
    }
   ]
  },
  { "title": "Query Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Collection Loaded Num",
   "type": "graph",
   "description": "Total number of the loaded collections in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_collection_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "DML Virtual Channel",
   "type": "graph",
   "description": "Total number of dml virtual channels for QueryNode watch",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_dml_vchannel_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Segment Loaded Num",
   "type": "graph",
   "description": "Total number of the loaded segment in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_segment_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id, segment_state)",
     "legendFormat": "{{pod}}-{{node_id}}-{{segment_state}}"
    }
   ]
  },
  {
   "title": "TimeTick Lag Behind Now (Consumed)",
   "type": "graph",
   "description": "Average, maximum and minimum values of the  timestamps for time tick behind.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_querynode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"timetick\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_querynode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"timetick\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_querynode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"timetick\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    }
   ]
  },
  {
   "title": "Search Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of searching requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querynode_sq_req_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (query_type, status, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{query_type}}-{{status}}"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "description": "per-second increasing rate of consuming message",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querynode_consume_msg_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (pod, node_id, msg_type)",
     "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_consume_msg_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-all"
    }
   ]
  },
  {
   "title": "Queryable Entity Num",
   "type": "graph",
   "description": "Total number of the queryable entities  in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_entity_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Segment Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search segment over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, query_type, segment_state) (rate(milvus_querynode_sq_segment_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}-{{segment_state}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_segment_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type, segment_state) / sum(increase(milvus_querynode_sq_segment_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type, segment_state)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}_{{segment_state}}"
    }
   ]
  },
  {
   "title": "Search Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search and query request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, query_type) (rate(milvus_querynode_sq_req_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_req_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type) / sum(increase(milvus_querynode_sq_req_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Search in Queue Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search or query in queue over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, query_type) (rate(milvus_querynode_sq_queue_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_queue_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type) / sum(increase(milvus_querynode_sq_queue_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Load Segment Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of load segment over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_load_segment_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_load_segment_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_load_segment_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Segcore Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search at the segcore step over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, query_type, pod, node_id) (rate(milvus_querynode_sq_core_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_core_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type) / sum(increase(milvus_querynode_sq_core_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Search Reduce Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search or query reduce over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, query_type) (rate(milvus_querynode_sq_reduce_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{query_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_reduce_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type) / sum(increase(milvus_querynode_sq_reduce_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id, query_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{query_type}}"
    }
   ]
  },
  {
   "title": "Ready Read Task Length",
   "type": "graph",
   "description": "The length of the task queue of read requests to be executed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_ready_len{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Flowgraph Num",
   "type": "graph",
   "description": "Total number of flowgraph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_flowgraph_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Unsolved Read Task Length",
   "type": "graph",
   "description": "The length of the task queue for unsolved read requests",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_unsolved_len{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group Size",
   "type": "graph",
   "description": "The number of original tasks contained in the merged search task",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_size_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_size_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_size_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Parallel Read Task Num",
   "type": "graph",
   "description": "Number of read requests currently being executed in parallel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_concurrency{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group NQ",
   "type": "graph",
   "description": "Number of queries for the merged search requests",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_nq_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_nq_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_nq_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-milvus_querynode_search_group_nq"
    }
   ]
  },
  {
   "title": "Search Top_K",
   "type": "graph",
   "description": "Top_K for search requests",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_topk_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_topk_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_topk_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search NQ",
   "type": "graph",
   "description": "Number of queries for search requests",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_nq_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_nq_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_nq_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group Top_K",
   "type": "graph",
   "description": "Top_K for the merged search requests.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_topk_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_topk_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_topk_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  { "title": "Data Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Data Node Num",
   "type": "graph",
   "description": "Number of data nodes which has register with etcd.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_datanode_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Segment Num",
   "type": "graph",
   "description": "Number of segments with different states in the Meta of DataCoord",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_segment_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (segment_state)",
     "legendFormat": "{{segment_state}}"
    }
   ]
  },
  {
   "title": "Stored Rows",
   "type": "graph",
   "description": "The number of rows of valid data accumulated in DataCoord that flushed.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_stored_rows_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "row"
    }
   ]
  },
  {
   "title": "Stored Binlog Size",
   "type": "graph",
   "description": "binlog size of all collections/segments, unit byte",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_stored_binlog_size{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Compact Segment Size",
   "type": "graph",
   "description": "Compacted segment size distribution buckets",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_compacted_segment_size_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    },
    {
     "expr": "sum(increase(milvus_datacoord_compacted_segment_size_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_datacoord_compacted_segment_size_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)"
    }
   ]
  },
  {
   "title": "Level-0 Segment Size",
   "type": "graph",
   "description": "Sum of Level-0 segment sizes",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_store_level0_segment_size_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    },
    {
     "expr": "sum(increase(milvus_datacoord_store_level0_segment_size_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_datacoord_store_level0_segment_size_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "graph",
   "description": "Number of ongoing DataCoord tasks",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_task_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Index Req Count",
   "type": "graph",
   "description": "DataCoord total index request count",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 143 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_index_req_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Index Node Number",
   "type": "graph",
   "description": "DataCoord total index node number.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 143 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_index_node_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "DataCoord Collection Number",
   "type": "graph",
   "description": "DataCoord total collection number.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_collection_num{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Channel Checkpoint Unix Seconds",
   "type": "graph",
   "description": "Latest checkpoint timestamp per channel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datacoord_channel_checkpoint_unix_seconds{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "size"
    }
   ]
  },
  { "title": "Data Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Flushed Data Rows",
   "type": "graph",
   "description": "DataNode total flushed rows count",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datanode_flushed_data_rows{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Consume Bytes Count",
   "type": "graph",
   "description": "DataNode total consumed bytes count",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datanode_consume_bytes_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "TimeTick Lag Behind Now (Consumed All)",
   "type": "graph",
   "description": "Average, maximum and minimum values of the  timestamps for time tick lag behind now.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 156 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_datanode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"all\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_datanode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"all\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_datanode_consume_tt_lag_ms{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\", msg_type=\"all\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    }
   ]
  },
  {
   "title": "Flush Operate Rate",
   "type": "graph",
   "description": "per-second increasing rate of flush operete.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_flush_buffer_op_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "description": "per-second increasing rate of consuming message",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 162 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_consume_msg_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (pod, node_id, msg_type)",
     "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "description": "per-second increasing rate of consuming message",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 162 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_consume_msg_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Consume Bytes Count",
   "type": "graph",
   "description": "Volume of data processed by DataNode",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datanode_consume_bytes_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (index_task_status)",
     "legendFormat": "{{index_task_status}}"
    }
   ]
  },
  {
   "title": "Autoflush Operate Rate",
   "type": "graph",
   "description": "per-second increasing rate of auto flush operate.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_autoflush_buffer_op_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
    }
   ]
  },
  {
   "title": "Msg Rows Consumed Rate",
   "type": "graph",
   "description": "per-second increasing rate of messages consumed for insert and delete operation.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 168 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_msg_rows_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (msg_type, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "description": "DataNode foreground flush buffer size",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_datanode_fg_buffer_size{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Save Data Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of writte the data in buffer to storage  over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_datanode_save_latency_bucket{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_datanode_save_latency_sum{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id) / sum(increase(milvus_datanode_save_latency_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Flush Data Size Rate",
   "type": "graph",
   "description": "per-second increasing rate of each message that has been flushed.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_flushed_data_size{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (msg_type, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
    }
   ]
  },
  {
   "title": "Write Data Count",
   "type": "graph",
   "description": "per-second count of write data.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_write_data_count{instance=~\"$instance\", container=\"$container\", namespace=\"$namespace\"}[2m])/120) by (status, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "CPU Usage Total",
   "type": "graph",
   "description": "Total cpu usage of all milvus components.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 187 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Goroutines Total",
   "type": "graph",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "process cpu usage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Process memory of milvus pod.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 193 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Allocated Memory",
   "type": "graph",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Max duration seconds",
   "type": "graph",
   "description": "GC Max duration seconds.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "graph",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Next GC Bytes",
   "type": "graph",
   "description": "Next GC Bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Opened Fds",
   "type": "graph",
   "description": "Number of process opened fds.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated Heap Objects",
   "type": "graph",
   "description": "Number of allocated heap objects.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Free Rate",
   "type": "graph",
   "description": "Rate of memory frees.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Memory mallocs rate.",
   "type": "graph",
   "description": "Rate of go memory mallocs.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Heap idle",
   "type": "graph",
   "description": "Number of heap bytes waiting to be used.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 211 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Allocated Rate",
   "type": "graph",
   "description": "Rate of bytes allocated, even if freed.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Heap released",
   "type": "graph",
   "description": "Number of heap bytes released to OS.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 217 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Heap in Use",
   "type": "graph",
   "description": "Number of heap bytes that be used.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 217 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"$container\", instance=~\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Threads",
   "type": "graph",
   "description": "Number of container threads created.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_threads{image=\"\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}