{
 "title": "KubeDB / ZooKeeper / Ensemble",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "ZooKeeper",
    "query": {
     "query": "label_values(kubedb_com_zookeeper_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} znode_count"
    },
    {
     "expr": "ephemerals_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(znode_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} znode_count_rate"
    },
    {
     "expr": "rate(ephemerals_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "global_sessions{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "local_sessions{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "write_per_namespace_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} write_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "read_per_namespace_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} read_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_received{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_sent{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} packets_sent"
    }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_packet_cache_misses{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} response_packet_cache_hits"
    },
    {
     "expr": "response_packet_get_children_cache_misses{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} response_packet_get_children_cache_misses"
    },
    {
     "expr": "response_packet_get_children_cache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} response_packet_get_children_cache_hits"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "digest_mismatches_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_txns_loaded_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dbinittime_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} db_init_time"
    }
   ]
  },
  { "title": "Quorum/Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "quorum_size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(quorum_size{namespace=~\"$namespace\",service=~\"$app+-stats\"})",
     "legendFormat": "quorum_size"
    }
   ]
  },
  {
   "title": "leader",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "leader_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader_uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "leader_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} leader_uptime"
    }
   ]
  },
  {
   "title": "learner/observer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(learners{namespace=~\"$namespace\",service=~\"$app+-stats\"})",
     "legendFormat": "learners"
    },
    {
     "expr": "max(synced_non_voting_followers{namespace=~\"$namespace\",service=~\"$app+-stats\"})",
     "legendFormat": "synced_non_voting_followers"
    },
    {
     "expr": "max(synced_observers{namespace=~\"$namespace\",service=~\"$app+-stats\"})",
     "legendFormat": "synced_observers"
    }
   ]
  },
  {
   "title": "commit_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "commit_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} commit_count"
    }
   ]
  },
  {
   "title": "snap_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snap_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} snap_count"
    }
   ]
  },
  {
   "title": "diff_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diff_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} diff_count"
    }
   ]
  },
  {
   "title": "looking_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "looking_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} looking_count"
    }
   ]
  },
  {
   "title": "proposal_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proposal_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} proposal_count"
    }
   ]
  },
  {
   "title": "proposal_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_proposal_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} last_proposal_size"
    },
    {
     "expr": "max_proposal_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} max_proposal_size"
    },
    {
     "expr": "min_proposal_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} min_proposal_size"
    }
   ]
  },
  {
   "title": "follower_sync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(follower_sync_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[1m])",
     "legendFormat": "{{instance}} follower_sync_time"
    }
   ]
  },
  {
   "title": "learner_handler_qp_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_handler_qp_size_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} learner_handler_qp_size_sum sid:{{key}}"
    }
   ]
  },
  {
   "title": "quit_leading_due_to_disloyal_voter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quit_leading_due_to_disloyal_voter{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} quit_leading_due_to_disloyal_voter"
    }
   ]
  },
  {
   "title": "Observer Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(om_commit_process_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} om_commit_process_time"
    },
    {
     "expr": "rate(om_proposal_process_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} om_proposal_process_time"
    }
   ]
  },
  { "title": "Session/Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watch_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} watch_count"
    }
   ]
  },
  {
   "title": "node_changed_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_changed_watch_count_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} node_changed_watch_count"
    }
   ]
  },
  {
   "title": "node_children_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_children_watch_count_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} node_children_watch_count"
    }
   ]
  },
  {
   "title": "node_deleted_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_deleted_watch_count_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} node_deleted_watch_count"
    }
   ]
  },
  {
   "title": "node_created_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_created_watch_count_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} node_created_watch_count"
    }
   ]
  },
  {
   "title": "revalidate_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "revalidate_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} revalidate_count"
    }
   ]
  },
  {
   "title": "stale_sessions_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stale_sessions_expired{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} stale_sessions_expired"
    }
   ]
  },
  {
   "title": "dead_watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dead_watchers_cleared{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} dead_watchers_cleared"
    },
    {
     "expr": "dead_watchers_queued{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} dead_watchers_queued"
    },
    {
     "expr": "rate(dead_watchers_cleaner_latency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} dead_watchers_cleaner_latency"
    }
   ]
  },
  {
   "title": "add_dead_watcher_stall_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "add_dead_watcher_stall_time{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} add_dead_watcher_stall_time"
    }
   ]
  },
  { "title": "Client/Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} outstanding_requests"
    }
   ]
  },
  {
   "title": "client_response_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "last_client_response_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} last_client_response_size"
    },
    {
     "expr": "min_client_response_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} min_client_response_size"
    },
    {
     "expr": "max_client_response_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} max_client_response_size"
    }
   ]
  },
  {
   "title": "bytes_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytes_received_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} bytes_received_count"
    }
   ]
  },
  {
   "title": "connection_request_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_request_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} connection_request_count"
    }
   ]
  },
  {
   "title": "num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} num_alive_connections"
    }
   ]
  },
  {
   "title": "connection_rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_rejected{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} connection_rejected"
    }
   ]
  },
  {
   "title": "connection_drop_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} connection_drop_count"
    }
   ]
  },
  {
   "title": "connection_drop_probability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_probability{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} connection_drop_probability"
    }
   ]
  },
  {
   "title": "sessionless_connections_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sessionless_connections_expired{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} sessionless_connections_expired"
    }
   ]
  },
  {
   "title": "connection_token_deficit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_token_deficit_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} connection_token_deficit"
    }
   ]
  },
  { "title": "Disk/Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "open_file_descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "open_file_descriptor_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsynctime_sum * 1000 /fsynctime_count{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} fsynctime_avg(μs)"
    },
    {
     "expr": "irate(fsynctime_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[1m])",
     "legendFormat": "{{instance}} fsynctime_rate"
    }
   ]
  },
  {
   "title": "snapshot_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(snapshottime_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} snapshot_time_rate"
    }
   ]
  },
  { "title": "Prep_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "prep_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_process_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} prep_process_time"
    }
   ]
  },
  {
   "title": "prep_processor_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 174 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} prep_processor_queue_time_ms"
    }
   ]
  },
  {
   "title": "prep_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_size_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} prep_processor_queue_size"
    }
   ]
  },
  {
   "title": "prep_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_request_queued{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} prep_processor_request_queued"
    }
   ]
  },
  {
   "title": "outstanding_changes_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_changes_queued{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} outstanding_changes_queued"
    },
    {
     "expr": "outstanding_changes_removed{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} outstanding_changes_removed"
    }
   ]
  },
  {
   "title": "close_session_prep_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(close_session_prep_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} close_session_prep_time"
    }
   ]
  },
  { "title": "Sync_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 } },
  {
   "title": "sync_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_process_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} sync_process_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_flush_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_flush_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} sync_processor_queue_flush_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_size_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} sync_processor_queue_size"
    }
   ]
  },
  {
   "title": "sync_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_request_queued{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} sync_processor_request_queued"
    }
   ]
  },
  {
   "title": "sync_processor_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_batch_size_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} sync_processor_batch_size"
    }
   ]
  },
  { "title": "Commit_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "commit_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_process_time_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} commit_process_time"
    },
    {
     "expr": "rate(read_commitproc_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} read_commitproc_time"
    },
    {
     "expr": "rate(write_commitproc_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} write_commitproc_time"
    }
   ]
  },
  {
   "title": "commit_proc_req_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_commit_proc_req_queued_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} write_commit_proc_req_queued"
    },
    {
     "expr": "rate(read_commit_proc_req_queued_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} read_commit_proc_req_queued"
    },
    {
     "expr": "rate(commit_commit_proc_req_queued_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} commit_commit_proc_req_queued"
    }
   ]
  },
  {
   "title": "requests_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_in_session_queue_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} requests_in_session_queue"
    }
   ]
  },
  {
   "title": "commit_proc_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_commit_proc_issued_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} read_commit_proc_issued"
    },
    {
     "expr": "rate(write_commit_proc_issued_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} write_commit_proc_issued"
    }
   ]
  },
  {
   "title": "concurrent_request_processing_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(concurrent_request_processing_in_commit_processor_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} concurrent_request_processing_in_commit_processor"
    }
   ]
  },
  {
   "title": "time_waiting_empty_pool_in_commit_processor_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} time_waiting_empty_pool_in_commit_processor_read"
    }
   ]
  },
  {
   "title": "pending_session_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pending_session_queue_size_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} pending_session_queue_size"
    }
   ]
  },
  {
   "title": "local_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_write_committed_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} local_write_committed_time_ms"
    }
   ]
  },
  {
   "title": "server_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_write_committed_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} server_write_committed_time"
    }
   ]
  },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_batch_time_in_commit_processor_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor"
    }
   ]
  },
  {
   "title": "reads_after_write_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_after_write_in_session_queue_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} reads_after_write_in_session_queue"
    }
   ]
  },
  {
   "title": "session_queues_drained",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(session_queues_drained_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} session_queues_drained"
    }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_issued_from_session_queue_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} reads_issued_from_session_queue"
    }
   ]
  },
  {
   "title": "request_commit_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_commit_queued{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} request_commit_queued"
    }
   ]
  },
  { "title": "Final_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 } },
  {
   "title": "write_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_final_proc_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} write_final_proc_time_ms"
    }
   ]
  },
  {
   "title": "read_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_final_proc_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} read_final_proc_time_ms"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 257 } },
  {
   "title": "read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(readlatency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} readlatency"
    }
   ]
  },
  {
   "title": "update_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(updatelatency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} updatelatency"
    }
   ]
  },
  {
   "title": "max_min_avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_latency{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} max_latency"
    },
    {
     "expr": "min_latency{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} min_latency"
    },
    {
     "expr": "avg_latency{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} avg_latency"
    }
   ]
  },
  {
   "title": "proposal_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proposal_latency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} proposal_latency"
    }
   ]
  },
  {
   "title": "quorum_ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(quorum_ack_latency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} quorum_ack_latency"
    }
   ]
  },
  {
   "title": "proposal_ack_creation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "proposal_ack_creation_latency{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} proposal_ack_creation_latency-{{quantile}}"
    }
   ]
  },
  {
   "title": "propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(propagation_latency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} propagation_latency"
    }
   ]
  },
  {
   "title": "commit_propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_propagation_latency_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} commit_propagation_latency"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 290 } },
  {
   "title": "tls_handshake",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 291 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tls_handshake_exceeded{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} tls_handshake_exceeded"
    },
    {
     "expr": "outstanding_tls_handshake{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} outstanding_tls_handshake"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 291 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} ensemble_auth_success"
    },
    {
     "expr": "ensemble_auth_skip{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} ensemble_auth_skip"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 299 } },
  {
   "title": "jvm_classes_loaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 300 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{namespace=~\"$namespace\",service=~\"$app+-stats\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 300 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_current{namespace=~\"$namespace\",service=~\"$app+-stats\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 300 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{namespace=~\"$namespace\",service=~\"$app+-stats\"})"
    }
   ]
  },
  {
   "title": "jvm_pause_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 308 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_pause_time_ms_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} jvm_pause_time_ms"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 308 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{instance}} gc:{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 308 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} state:{{state}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{instance}} pool:{{pool}}"
    }
   ]
  }
 ]
}