{
 "title": "KubeDB / Druid / Database",
 "description": "KubeDB Managed Druid Grafana Dashboard that captures metrics emitted by Druid builtin prometheus exporter.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kubedb_com_druid_created{druid=~\".+\",namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Druid Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Druid Status",
   "type": "stat",
   "description": "Metric indicating the druid service is up.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(druid_service_heartbeat{service=\"$app-stats\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Connection",
   "type": "stat",
   "description": "Indicator of connection status. 1 for connected, 0 for disconnected. Emitted once per monitor period.",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(druid_zk_connected{service=\"$app-stats\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "description": "Number of total datasources",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(count(count_values(\"dataSource\", druid_segment_size{service=\"$app-stats\", namespace=\"$namespace\"})))"
    }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "description": "Number of segments to load.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_segment_loadqueue_count{service=\"$app-stats\", namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Sucess Tasks",
   "type": "stat",
   "description": "Number of task actions that were executed successfully during the emission period.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time(druid_task_success_count_created{service=\"$app-stats\", namespace=\"$namespace\"}[$__range])",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Total Segment Size",
   "type": "stat",
   "description": "Total size of used segments in all the data sources.",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_size{service=\"$app-stats\", namespace=\"$namespace\"}) / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "description": "Size in bytes of segments to load.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_loadqueue_size{service=\"$app-stats\", namespace=\"$namespace\"}) / (1024 * 1024)"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "description": "Used memory",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_mem_used{service=\"$app-stats\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "description": "Pool used",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_pool_used{service=\"$app-stats\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Bufferpool Count",
   "type": "timeseries",
   "description": "Bufferpool count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "druid_jvm_bufferpool_count{bufferpoolName=\"direct\", service=\"$app-stats\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Cpu Total",
   "type": "gauge",
   "description": "Count of CPU time in Nanoseconds spent on garbage collection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "druid_jvm_gc_cpu_total{service=\"$app-stats\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Druid Datasource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Datasource Size",
   "type": "stat",
   "description": "Total size of used segments.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_size{service=\"$app-stats\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Datasource Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_segment_size{service=\"$app-stats\", namespace=\"$namespace\"}[$__range])) by (dataSource)",
     "legendFormat": "{{dataSource}}"
    }
   ]
  },
  { "title": "Query Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Query Time Histogram (Seconds taken to complete a query)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(le) (druid_query_time_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Druid Query Wait Time Histogram (Seconds waiting for a segment to be scanned)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(le) (druid_query_wait_time_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}