{
 "title": "KubeDB / Memcache / Pod",
 "description": "Memcache metrics dashboard for Kubernetes created with KubeDB and Prometheus metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(memcached_up, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "% Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{pod=\"$pod\",status=\"hit\"}[1m]))/sum(rate(memcached_commands_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{pod=\"$pod\"}[1m]) * 60) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "% Get Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{pod=\"$pod\",command=\"get\"}[1m]))/sum(rate(memcached_commands_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "get ratio"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_connections{pod=\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "memcached_max_connections{pod=\"$pod\"} - memcached_current_connections{pod=\"$pod\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memcached_current_bytes{pod=\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "memcached_limit_bytes{pod=\"$pod\"}-memcached_current_bytes{pod=\"$pod\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Items",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_items{pod=\"$pod\"}",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_evicted_total{pod=\"$pod\"}[1m])*60",
     "legendFormat": "evictions"
    }
   ]
  },
  {
   "title": "Reclaimed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_items_reclaimed_total{pod=\"$pod\"}[1m])*60",
     "legendFormat": "reclaimed"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(memcached_read_bytes_total{pod=\"$pod\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(memcached_written_bytes_total{pod=\"$pod\"}[1m])",
     "legendFormat": "write"
    }
   ]
  }
 ]
}