{
 "title": "Memcached Overview",
 "description": "Memcached Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(memcached_up, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_uptime_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_current_connections{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(memcached_commands_total{job=\"coreos-prom-memcd-stats\"}[15m]))/15"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_current_bytes{job=\"$job\"}/memcached_limit_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "memcached_current_items{job=\"$job\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(memcached_commands_total{job=\"coreos-prom-memcd-stats\"}[15m]))/15",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "memcached_current_connections{job=\"$job\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "delta(memcached_read_bytes_total{job=\"$job\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "delta(memcached_written_bytes_total{job=\"$job\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Command",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (delta(memcached_commands_total{job=\"$job\", status=\"hit\"}[1m]))  / sum (delta(memcached_commands_total{job=\"$job\"}[1m])) * 100",
       "legendFormat": "Hit Ratio"
      }
     ]
    },
    {
     "title": "Hit Ratio Per Command",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (delta(memcached_commands_total{job=\"$job\", status=\"hit\",command=\"get\"}[1m]))  / sum (delta(memcached_commands_total{job=\"$job\",command=\"get\"}[1m])) * 100",
       "legendFormat": "get"
      },
      {
       "expr": "sum (delta(memcached_commands_total{job=\"$job\", status=\"hit\",command=\"delete\"}[1m]))  / sum (delta(memcached_commands_total{job=\"$job\",command=\"delete\"}[1m])) * 100",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "Command Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(memcached_commands_total{job=\"$job\"}[1m])) by (command)",
       "legendFormat": "{{ command }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "reclaimed / evicted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(memcached_items_reclaimed_total{job=\"$job\"}[1m])",
       "legendFormat": "reclaimed"
      },
      {
       "expr": "delta(memcached_items_evicted_total{job=\"$job\"}[1m])",
       "legendFormat": "evicted"
      }
     ]
    }
   ]
  }
 ]
}