{
 "title": "KubeDB / Oracle / Database",
 "tags": [
  "galera",
  "oracle"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Oracle",
    "query": {
     "query": "label_values(kubedb_com_oracle_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "oracledb_uptime_uptime_seconds{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "AG Cluster Active Replica",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_ag_cluster_size_cluster_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_pod_role_role_status{namespace=~\"$namespace\",service=~\"$app+-stats\",role=\"PRIMARY\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Role",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_pod_role{namespace=~\"$namespace\", service=~\"$app+-stats\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status{namespace=~\"$namespace\",service=~\"$app+-stats\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_pod_role{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "SQL Compilations/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_compilations_compilations_total{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Batch Requests per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_batch_requests_batch_requests_total{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SQL Server log growths",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_log_growth_archived_logs_bytes{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "SQL Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_connections_sessions_current{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "mssql_io_stall_total_seconds{}", "legendFormat": "{{db}}" }
   ]
  }
 ]
}