{
 "title": "KubeDB / Oracle / Pod",
 "description": "Works with and awaragi/prometheus-mssql-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "query": { "query": "label_values(oracledb_up, job)" } },
   {
    "name": "database",
    "query": {
     "query": "label_values(oracledb_connections_sessions_current,db)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "oracle",
    "query": {
     "query": "query_result(kubedb_com_oracle_created{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(up{job=\"$Job\",namespace=~\"$namespace\",pod=~\"${app}-.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_pod_role_role_status{pod=~\"$pod\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(oracledb_uptime_uptime_seconds{pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(oracledb_local_time_local_time_seconds{job=~\"$Job\", pod=\"$pod\"}*1000)"
    },
    {
     "expr": "oracledb_os_memory_total_memory_total_bytes{job=~\"$Job\", pod=\"$pod\"}"
    },
    {
     "expr": "mssql_os_memory{state=\"used\",job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_os_page_file{state=\"available\",job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_os_page_file{state=\"used\",job=~\"$Job\", pod=\"$pod\"}-0"
    }
   ]
  },
  {
   "title": "Server Resouce Overview",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(oracledb_buffer_cache_physical_reads_total{job=~\"$Job\", pod=\"$pod\"}[5m]) - 0",
     "legendFormat": "Total page faults"
    },
    {
     "expr": "rate(oracledb_batch_requests_batch_requests_total{job=~\"$Job\", pod=\"$pod\"}[5m]) - 0"
    },
    {
     "expr": "oracledb_buffer_cache_hit_ratio_cache_hit_ratio{job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "rate(oracledb_deadlocks_deadlocks_total{job=~\"$Job\", pod=\"$pod\"}[5m]) - 0"
    },
    {
     "expr": "rate(oracledb_user_errors_user_errors_total{job=~\"$Job\", pod=\"$pod\"}[5m]) - 0"
    },
    {
     "expr": "mssql_kill_connection_errors{job=~\"$Job\", pod=\"$pod\"}-0"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Current database connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_connections_sessions_current{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "DB Log growth since last restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_log_growth_archived_logs_bytes{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_system_io{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database I/O wait of stall detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "repeat": "database",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_user_io{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  }
 ]
}