{
 "title": "ACE / Falco / Cluster Events",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster FalcoEvents Total",
   "type": "graph",
   "description": "Total number of Falco Events occurred in cluster scope",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (falco_appscode_com_events)",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "Cluster FalcoEvents  by Priority",
   "type": "graph",
   "description": "Total number of Falco events occurred in cluster scope by priority",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(priority) (falco_appscode_com_events)",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Cluster FalcoEvents  by Rule",
   "type": "graph",
   "description": "Total number of Falco events occurred in cluster scope by rule",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(rule) (falco_appscode_com_events)",
     "legendFormat": "{{ rule }}"
    }
   ]
  }
 ]
}