{
 "title": "ACE / Falco / Node Events",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node FalcoEvents total",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in node scope",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (falco_appscode_com_events{node=\"$node\"})",
     "legendFormat": "{{ target_node }}"
    }
   ]
  },
  {
   "title": "Node FalcoEvents by Priority",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in node scope by priority",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (priority) (falco_appscode_com_events{node=\"$node\"})",
     "legendFormat": " {{ priority }}"
    }
   ]
  },
  {
   "title": "Node FalcoEvents by Rule",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in node scope by rule",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (rule) (falco_appscode_com_events{node=\"$node\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  }
 ]
}