{
 "title": "KubeStash / Dashboard",
 "description": "Grafana dashboard for KubeStash",
 "tags": [
  "kubestash",
  "backup",
  "restore"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_created,namespace)"
    }
   },
   {
    "name": "target_kind",
    "label": "Target Kind",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_created{namespace=~\"${namespace}\"},target_kind)"
    }
   },
   {
    "name": "target_name",
    "label": "Target Name",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_created{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\"}, target_name)"
    }
   },
   {
    "name": "target_namespace",
    "label": "Target Namespace",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_created{namespace=~\"${namespace}\",target_kind=~\"${target_kind}\",target_name=~\"${target_name}\"},target_namespace)"
    }
   },
   {
    "name": "backup_invoker_kind",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_phase{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\",target_namespace=~\"${target_namespace}\"},backup_invoker_kind)"
    }
   },
   {
    "name": "backup_invoker_name",
    "query": {
     "query": "label_values(core_kubestash_com_backupconfiguration_phase{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\",target_namespace=~\"${target_namespace}\"},backup_invoker_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Storage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BackupStorage",
   "type": "table",
   "description": "List of BackupStorages currently exist in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "storage_kubestash_com_backupstorage_info{namespace=~\"${namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_backupstorage_size_bytes{namespace=~\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "BackupStorage Sizes",
   "type": "graph",
   "description": "Graph showing how BackupStorage size grows over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "storage_kubestash_com_backupstorage_size_bytes{namespace=~\"${namespace}\"}",
     "legendFormat": "{{namespace}}/{{invoker_name}}"
    }
   ]
  },
  { "title": "Backup Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Applications",
   "type": "stat",
   "description": "Number of applications that has been configured for backup",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_backupconfiguration_phase{namespace=~\"${namespace}\", phase=~\"Ready\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"})"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "stat",
   "description": "Total number of successful backup",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_backupsession_info{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Running Backups",
   "type": "stat",
   "description": "Number of backup sessions that are currently running",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_backupsession_info{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Skipped Backups",
   "type": "stat",
   "description": "Number of backup sessions that have been skipped",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_backupsession_info{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\", phase=\"Skipped\"})"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "description": "Number of backups that have failed",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_backupsession_info{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "stat",
   "description": "Total size of the backed up data",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storage_kubestash_com_repository_size_bytes{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"})"
    }
   ]
  },
  {
   "title": "Backup Targets",
   "type": "table",
   "description": "A list of backup targets",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "core_kubestash_com_backupconfiguration_sessions{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    }
   ]
  },
  {
   "title": "Recent Backups",
   "type": "table",
   "description": "List of BackupSessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "core_kubestash_com_backupsession_info{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "core_kubestash_com_backupsession_duration_seconds{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "core_kubestash_com_backupsession_created{namespace=~\"${namespace}\", backup_invoker_kind=~\"${backup_invoker_kind}\", backup_invoker_name=~\"${backup_invoker_name}\"} * 1000"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "table",
   "description": "List of Repositories",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "storage_kubestash_com_repository_size_bytes{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_repository_snapshot_count_total{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_repository_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_repository_last_successful_backup{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} * 1000"
    }
   ]
  },
  {
   "title": "Repository Sizes",
   "type": "graph",
   "description": "Graph showing how Repository size grows over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "storage_kubestash_com_repository_size_bytes{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}",
     "legendFormat": "{{namespace}}/{{invoker_name}}"
    }
   ]
  },
  {
   "title": "Recent Snapshots",
   "type": "table",
   "description": "List of Snapshots",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "storage_kubestash_com_snapshot_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_snapshot_component_count_total{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "storage_kubestash_com_snapshot_time_seconds{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} * 1000"
    },
    {
     "expr": "storage_kubestash_com_snapshot_size_bytes{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    }
   ]
  },
  { "title": "Restore Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Total Restore Count",
   "type": "stat",
   "description": "Number of total restore done within the time-frame",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_restoresession_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"})"
    }
   ]
  },
  {
   "title": "Successful Restores",
   "type": "stat",
   "description": "Total number of successful restores",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_restoresession_phase{namespace=~\"${namespace}\", phase=~\"Succeeded\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} == 1)"
    }
   ]
  },
  {
   "title": "Running Restores",
   "type": "stat",
   "description": "Number of restore sessions that are currently running",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_restoresession_phase{namespace=~\"${namespace}\", phase=~\"Running\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} == 1)"
    }
   ]
  },
  {
   "title": "Pending Restores",
   "type": "stat",
   "description": "Number of restore sessions that are currently pending to run",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_restoresession_phase{namespace=~\"${namespace}\", phase=~\"Pending\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Restores",
   "type": "stat",
   "description": "Number of restore sessions that have failed",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(core_kubestash_com_restoresession_phase{namespace=~\"${namespace}\", phase=~\"Failed\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} == 1)"
    }
   ]
  },
  {
   "title": "Recent Restores",
   "type": "table",
   "description": "List of current RestoreSession in the cluster",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "core_kubestash_com_restoresession_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "core_kubestash_com_restoresession_duration_seconds{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"}"
    },
    {
     "expr": "core_kubestash_com_restoresession_created{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\", target_namespace=~\"${target_namespace}\"} * 1000"
    }
   ]
  },
  { "title": "KubeStash Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage of KubeStash Operator",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=~\"operator\", pod=~\".*kubestash.*\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage of KubeStash Operator",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"operator\", pod=~\".*kubestash.*\"})by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}