{
 "title": "KubeDB / RabbitMQ / Pod",
 "description": "rabbitmq Dashboard for Prometheus rabbitmq Exporter 1.x, it works with helm stable/rabbitmq-ha exporter.\r\n\r\nIf you missing rabbitmq memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "rabbitmq",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "RabbitMQ",
    "query": {
     "query": "label_values(kubedb_com_rabbitmq_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(rabbitmq_build_info{namespace=~\"$namespace\",pod=~\"${app}-.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\"$pod\",phase=~\"Running\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(rabbitmq_erlang_uptime_seconds{pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Unreachable Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_unreachable_cluster_peers_count{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Persistent messages Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_persistent{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Ready and unacknowledged messages stored in memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ram{pod=~\"$pod\"}",
     "legendFormat": "messages stored in ram"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_connections{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Size of ready and unacknowledged messages stored in memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ram_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Size in bytes of persistent messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_persistent{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Erlang GC runs Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_erlang_gc_runs_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "Number of total GC runs"
    }
   ]
  },
  {
   "title": "Memory reclaimed by Erlang GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_erlang_gc_reclaimed_bytes_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Messages published / s",
   "type": "timeseries",
   "description": "The incoming message rate before any routing rules are applied.\n\nIf this value is lower than the number of messages published to queues, it may indicate that some messages are delivered to more than one queue.\n\nIf this value is higher than the number of messages published to queues, messages cannot be routed and will either be dropped or returned to publishers.\n\n* [Publishers](https://www.rabbitmq.com/publishers.html)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{pod=\"$pod\", namespace=\"$namespace\"}) by(rabbitmq_node)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_disk_space_available_bytes{pod=~\"$pod\"} / 1024 / 1024",
     "legendFormat": "Available memory"
    },
    {
     "expr": "rabbitmq_process_resident_memory_bytes{pod=~\"$pod\"} / 1024 / 1024",
     "legendFormat": "used memory"
    }
   ]
  },
  { "title": "CPU And memory Usage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Memory Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"}) / 1024 / 1024",
     "legendFormat": "used memory"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) / count(node_cpu_seconds_total{mode=\"system\"}) * 100",
     "legendFormat": "CPU used (%)"
    }
   ]
  }
 ]
}