{
 "title": "KubeDB / Pgpool / Database",
 "tags": [
  "db",
  "stats",
  "kubedb",
  "pgpool"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Pgpool",
    "query": {
     "query": "label_values(kubedb_com_pgpool_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pgpool2_up{namespace=~\"$namespace\", service=~\"$app-stats\"}, pod)"
    }
   },
   {
    "name": "backend_nodes",
    "query": {
     "query": "label_values(pgpool2_pool_nodes_status{namespace=~\"$namespace\",pod=~\"$pod\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backend PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Status",
   "type": "stat",
   "description": "For each Pgpool it shows the status of backend Primary and Standby PostgreSQL server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_status{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}} )"
    }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "description": "Replication delay of backend PosgreSQL servers",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_replication_delay{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  { "title": "Child Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Connections Ratio",
   "type": "timeseries",
   "description": "Ratio of used child processes to total child processes (0.0 to 1.0)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_frontend_used_ratio{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connectios",
   "type": "piechart",
   "description": "Number of total and used child processes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (pgpool2_frontend_used{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}  (Used child process)"
    },
    {
     "expr": "pgpool2_frontend_total{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} (Total child process)"
    }
   ]
  },
  { "title": "Error Message Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Error Message Counts",
   "type": "timeseries",
   "description": "Error message counts returned from backend PostgreSQL",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_error_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Fatal Message Counts",
   "type": "timeseries",
   "description": "Fatal message counts returned from backend PostgreSQL",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_fatal_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Panic Message Counts",
   "type": "timeseries",
   "description": "Panic message counts returned from backend PostgreSQL",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_panic_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  { "title": "SQL Command Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "SELECT statement counts",
   "type": "timeseries",
   "description": "SELECT statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_select_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "DELETE statement counts",
   "type": "timeseries",
   "description": "DELETE statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_delete_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "INSERT statement counts",
   "type": "timeseries",
   "description": "INSERT statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_insert_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "UPDATE statement counts",
   "type": "timeseries",
   "description": "UPDATE statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_update_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "DDL statement counts",
   "type": "timeseries",
   "description": "DDL statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_ddl_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Other statement counts",
   "type": "timeseries",
   "description": "Other statement counts issued to each backend PostgreSQL",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_other_cnt{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Query Cache Hit Ratio",
   "type": "timeseries",
   "description": "Query cache hit ratio",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_cache_hit_ratio{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of used cache entries",
   "type": "timeseries",
   "description": "Number of used cache entries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_num_cache_entries{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hash entries count",
   "type": "timeseries",
   "description": "Number of total and used hash entries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_num_hash_entries{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} (Total hash entries)"
    },
    {
     "expr": "pgpool2_pool_cache_used_hash_entries{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} (Used hash entries)"
    }
   ]
  },
  {
   "title": "Hash entries size",
   "type": "timeseries",
   "description": "Total size in bytes of used and free cache size",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_free_cache_entries_size{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} (Free hash entries)"
    },
    {
     "expr": "pgpool2_pool_cache_used_cache_entries_size{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} (Used hash entries)"
    }
   ]
  },
  {
   "title": "Missed SELECT query from cache",
   "type": "timeseries",
   "description": "The number of SELECT that did not hit against the query",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_num_selects{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total size of fragmented cache",
   "type": "timeseries",
   "description": "Total size in bytes of the fragmented cache",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_fragment_cache_entries_size{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "PostgreSQL Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Number of health check count in total",
   "type": "timeseries",
   "description": "Number of health check count in total",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_total_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of Successful Health Check ",
   "type": "timeseries",
   "description": "Number of successful health check count in total",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 53 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_success_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of failed health check",
   "type": "timeseries",
   "description": "Number of failed health check count in total",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_fail_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of skipped health check",
   "type": "timeseries",
   "description": "Number of skipped health check count in total",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 53 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_skip_count{hostname=~\"$backend_nodes\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of retried health check",
   "type": "timeseries",
   "description": "Number of retried health check count in total",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_retry_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of maximum retried health check",
   "type": "timeseries",
   "description": "Number of maximum retried health check count in a health check session",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_retry_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of average retried health check",
   "type": "timeseries",
   "description": "Number of average retried health check count in a health check session",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 58 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_retry_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Average health check duration",
   "type": "timeseries",
   "description": "Average health check duration in Millie seconds",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_duration{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Minimum health check duration",
   "type": "timeseries",
   "description": "Minimum health check duration in Millie seconds",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_min_duration{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Maximum health check duration",
   "type": "timeseries",
   "description": "Maximum health check duration in Millie seconds",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_duration{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  }
 ]
}