{
 "title": "KubeDB / PgBouncer / Database",
 "tags": [
  "db",
  "stats",
  "kubedb",
  "pgbouncer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "PgBouncer",
    "query": {
     "query": "label_values(kubedb_com_pgbouncer_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pgbouncer_up{namespace=~\"$namespace\", service=~\"$app-stats\"}, pod)"
    }
   },
   {
    "name": "backend_nodes",
    "query": {
     "query": "label_values(pgbouncer_pool_nodes_status{namespace=~\"$namespace\",pod=~\"$pod\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PGBouncer Disabled",
   "type": "stat",
   "description": "For each PgBouncer it shows if the Database is disabled",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_disabled{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}))/2",
     "legendFormat": "{{pod}} ({{role}} )"
    }
   ]
  },
  {
   "title": "PGBouncer Status",
   "type": "stat",
   "description": "For each PgBouncer it shows if the Database is paused",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_paused{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}))/2",
     "legendFormat": "{{pod}} ({{role}} )"
    }
   ]
  },
  { "title": "Backend Database Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Connections Ratio",
   "type": "timeseries",
   "description": "Ratio of used child processes to total child processes (0.0 to 1.0)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))/(sum by (pod) (pgbouncer_databases_max_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Database Connectios",
   "type": "piechart",
   "description": "Number of total backend database connected",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))-(sum by (pod) (pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\", name=\"pgbouncer\"}))",
     "legendFormat": "{{pod}}  (Used child process)"
    },
    {
     "expr": "pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\", name=\"pgbouncer\"}",
     "legendFormat": "{{pod}} (Total child process)"
    }
   ]
  },
  { "title": "Error Message Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Error Message Counts",
   "type": "timeseries",
   "description": "Error message counts returned from backend PostgreSQL",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pgbouncer_config_log_pooler_errors{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  { "title": "Query Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Query Count",
   "type": "timeseries",
   "description": "Total number of Query",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_stats_query_count_total{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Query time in Microseconds",
   "type": "stat",
   "description": "Average Query Time in microseconds within stat period",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_stats_avg_query_time_microseconds{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Query Timeout in Seconds",
   "type": "stat",
   "description": "Amount of Seconds for Timeout of an Query",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_config_query_wait_timeout_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Time Of Query Execution",
   "type": "stat",
   "description": "Total number of Microseconds Connecting Postgresql, Executing Query",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_stats_query_time_microseconds_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Transaction Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Average of Total Transaction",
   "type": "gauge",
   "description": "Average Transaction Count",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_stats_avg_xact_count{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "Total Number Of Transaction",
   "type": "timeseries",
   "description": "Total Number of Transaction",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_stats_xact_count_total{hostname=~\"$backend_nodes\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  }
 ]
}