{
 "title": "KubeDB / PgBouncer / Pod",
 "tags": [
  "db",
  "stats",
  "kubedb",
  "pgbouncer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "PgBouncer",
    "query": {
     "query": "label_values(kubedb_com_pgbouncer_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pgbouncer_up{namespace=~\"$namespace\", service=~\"$app-stats\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Name",
   "type": "stat",
   "description": "Running PgBouncer pod names",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PgBouncer Pod Uptime",
   "type": "stat",
   "description": "Uptime of each PgBouncer pod",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage of each PgBouncer pod",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage of each PgBouncer pod",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Connection Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total possible connections",
   "type": "stat",
   "description": "Total possible connection each PgBouncer pod can make",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_max_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Opened connections",
   "type": "stat",
   "description": "Currently opened connection for each PgBouncer pod",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_config_max_db_connections{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections in use",
   "type": "stat",
   "description": "Currently used connection for each PgBouncer pod",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ratio of used connections",
   "type": "graph",
   "description": "Ratio of backend connections in use to total backend connection slot",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (pgbouncer_databases_current_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))/(sum by (pod) (pgbouncer_databases_max_connections{namespace=~\"$namespace\",pod=~\"$pod\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Scrape Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Last Scrape",
   "type": "stat",
   "description": "Show the status if last scrape to the exporter was successful or not",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_last_scrape_error{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Scrape Duration",
   "type": "graph",
   "description": "Last scrape duration in PgBouncer exporter",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_last_scrape_duration_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Scrapes",
   "type": "stat",
   "description": "Total scareps till now",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_scrapes_total{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}