{
 "title": "KubeDB / MSSQLServer / Pod",
 "description": "Works with and awaragi/prometheus-mssql-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(mssql_local_time_seconds, job)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(mssql_connections,db)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{target=\"mssqlserver_database\"}, namespace)"
    }
   },
   {
    "name": "app",
    "label": "mssqlserver",
    "query": {
     "query": "query_result(kubedb_com_mssqlserver_created{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(up{target=\"mssqlserver_database\",namespace=~\"$namespace\",pod=~\"${app}-.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_hostname{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\", target=\"mssql_database\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_pod_role{pod=~\"$pod\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mssql_uptime_seconds{pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(mssql_local_time_seconds{job=~\"$Job\", pod=\"$pod\"}*1000)"
    },
    {
     "expr": "mssql_os_memory{state=\"available\",job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_os_memory{state=\"used\",job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_os_page_file{state=\"available\",job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_os_page_file{state=\"used\",job=~\"$Job\", pod=\"$pod\"}-0"
    }
   ]
  },
  {
   "title": "Server Resouce Overview",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "mssql_page_fault_count{job=~\"$Job\", pod=\"$pod\"}-0",
     "legendFormat": "Total page faults"
    },
    {
     "expr": "mssql_batch_requests{job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_page_life_expectancy_seconds{job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_deadlocks{job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_user_errors{job=~\"$Job\", pod=\"$pod\"}-0"
    },
    {
     "expr": "mssql_kill_connection_errors{job=~\"$Job\", pod=\"$pod\"}-0"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Current database connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_connections{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "DB Log growth since last restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_log_growths{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_total_seconds{pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database I/O wait of stall detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "repeat": "database",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{db=\"$database\", pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{db=\"$database\", pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{db=\"$database\", pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{db=\"$database\", pod=\"$pod\"}",
     "legendFormat": "{{db}}"
    }
   ]
  }
 ]
}