{
 "title": "KubeDB / PerconaXtraDB / Galera-Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
   },
   {
    "name": "app",
    "label": "PerconaXtraDB",
    "query": "label_values(mysql_up{namespace=~\"$namespace\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(wsrep_cluster_name)(mysql_galera_variables_info{namespace=~\"$namespace\",service=~\"$app\"})",
     "legendFormat": "{{wsrep_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Members",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod)(mysql_galera_variables_info{namespace=~\"$namespace\",service=~\"$app\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Replication Delay Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average: Galera Replication Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(mysql_galera_evs_repl_latency_avg_seconds{namespace=~\"$namespace\",service=~\"$app\"}[5m])",
     "legendFormat": "{{pod}} - Latency Average"
    }
   ]
  },
  {
   "title": "Standard Deviation: Galera Replication Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_galera_evs_repl_latency_stdev{namespace=~\"$namespace\",service=~\"$app\"}[1m])",
     "legendFormat": "{{pod}} - Latency Average"
    }
   ]
  },
  {
   "title": "Sample Size: Galera Replication Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_galera_evs_repl_latency_sample_size{namespace=~\"$namespace\",service=~\"$app\"}[1m])",
     "legendFormat": "{{pod}} - Latency Average"
    }
   ]
  }
 ]
}