{
 "title": "Galera/MariaDB - Overview",
 "description": "mariadb galera cluster overview. metrics from mysqld exporter.",
 "tags": [
  "mysql",
  "galera",
  "mariadb"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "job", "query": { "query": "label_values(mysql_up, job)" } },
   { "name": "pod", "query": { "query": "label_values(mysql_up, pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_up{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Current - {{ pod }}"
    },
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Max - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads[10m])",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes[10m])",
     "legendFormat": "write - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL network received vs sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "received - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "sent - {{ pod }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, rate(mysql_global_status_commands_total[5m]))",
     "legendFormat": "{{ pod }} = '{{ command }}'"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_files[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_open_files", "legendFormat": "Open Files - {{ pod }}" },
    {
     "expr": "mysql_global_variables_open_files_limit",
     "legendFormat": "Open Files Limit - {{ pod }}"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files",
     "legendFormat": "InnoDB Open Files - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_slow_queries[1m])",
     "legendFormat": "Slow Queries on {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_connects[1m])",
     "legendFormat": "Aborted Connects (attempts) on - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_aborted_clients[1m])",
     "legendFormat": "Aborted Clients (timeout) on - {{ pod }}"
    }
   ]
  }
 ]
}