{
 "title": "KubeDB / MariaDB / Database",
 "tags": [
  "galera",
  "mariadb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
   },
   {
    "name": "app",
    "label": "MariaDB",
    "query": "label_values(kubedb_com_mariadb_status_phase{namespace=~\"$namespace\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_up{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status{namespace=~\"$namespace\",service=~\"$app+-stats\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Current - {{ pod }}"
    },
    {
     "expr": "mysql_global_variables_max_connections{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Max - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_reads{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_writes{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "write - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL network received vs sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "received - {{ pod }}"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "sent - {{ pod }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, rate(mysql_global_status_commands_total{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m]))",
     "legendFormat": "{{ pod }} = '{{ command }}'"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_files{namespace=~\"$namespace\",service=~\"$app+-stats\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_files{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Open Files - {{ pod }}"
    },
    {
     "expr": "mysql_global_variables_open_files_limit{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Open Files Limit - {{ pod }}"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "InnoDB Open Files - {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{namespace=~\"$namespace\",service=~\"$app+-stats\"}[1m])",
     "legendFormat": "Slow Queries on {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_aborted_connects{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "Aborted Connects (attempts) on - {{ pod }}"
    },
    {
     "expr": "rate(mysql_global_status_aborted_clients{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "Aborted Clients (timeout) on - {{ pod }}"
    }
   ]
  }
 ]
}