{
 "title": "KubeDB / MariaDB / Standard Replication",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "MariaDB",
    "query": {
     "query": "label_values(kubedb_com_mariadb_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Master Server ID",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_master_server_id{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Slaves Connected",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_slaves_connected{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replica SQL Thread Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replica IO Thread Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Replication Error Number",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mysql_slave_status_last_errno{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Replication SQL Error Number",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "mysql_slave_status_last_sql_errno{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Replication IO Error Number",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "mysql_slave_status_last_io_errno{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replication Lag (Seconds)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Max Relay Log Size",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "mysql_slave_status_max_relay_log_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Relay Log Position",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "mysql_slave_status_relay_log_pos{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Transactional Groups Processed (Rate)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_slave_status_slave_transactional_groups{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Non-Transactional Groups Processed (Rate)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_slave_status_slave_non_transactional_groups{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Replication Error Message",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "mysql_slave_status_last_io_error{namespace=~\"$namespace\",service=~\"$app+-stats\"} or mysql_slave_status_last_sql_error{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }} - Error"
    }
   ]
  }
 ]
}