{
 "title": "KubeDB / MySQL / Database",
 "description": "mariadb galera cluster overview. metrics from mysqld exporter.",
 "tags": [
  "mysql",
  "database"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "mysql",
    "query": {
     "query": "label_values(mysql_up{namespace=~\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_up{namespace=~\"$namespace\",service=~\"$mysql\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=~\"$namespace\",service=~\"$mysql\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_queries{namespace=~\"$namespace\",service=~\"$mysql\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(mysql_global_status_max_used_connections{namespace=~\"$namespace\",service=~\"$mysql\"})",
     "legendFormat": "Current - {{service}}"
    },
    {
     "expr": "sum by (service) (mysql_global_variables_max_connections{namespace=~\"$namespace\",service=~\"$mysql\"})",
     "legendFormat": "Max -  {{service}}"
    }
   ]
  },
  {
   "title": "MySQL  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_innodb_data_reads{namespace=~\"$namespace\",service=~\"$mysql\"}[10m]))",
     "legendFormat": "reads - {{ service }}"
    },
    {
     "expr": "sum by (service) (rate(mysql_global_status_innodb_data_writes{namespace=~\"$namespace\",service=~\"$mysql\"}[10m]))",
     "legendFormat": "write - {{ service }}"
    }
   ]
  },
  {
   "title": "MySQL network received vs sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$mysql\"}[5m]))",
     "legendFormat": "received - {{ service }}"
    },
    {
     "expr": "sum by (service) (rate(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$mysql\"}[5m]))",
     "legendFormat": "sent - {{ service }}"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_opened_files{namespace=~\"$namespace\",service=~\"$mysql\"}[5m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (mysql_global_status_open_files{namespace=~\"$namespace\",service=~\"$mysql\"})",
     "legendFormat": "Open Files - {{ service }}"
    },
    {
     "expr": "sum by (service) (mysql_global_variables_open_files_limit{namespace=~\"$namespace\",service=~\"$mysql\"})",
     "legendFormat": "Open Files Limit - {{ service }}"
    },
    {
     "expr": "sum by (service) (mysql_global_status_innodb_num_open_files{namespace=~\"$namespace\",service=~\"$mysql\"})",
     "legendFormat": "InnoDB Open Files - {{ service }}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_slow_queries{namespace=~\"$namespace\",service=~\"$mysql\"}[5m]))",
     "legendFormat": "Slow Queries on {{ service }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(mysql_global_status_aborted_connects{namespace=~\"$namespace\",service=~\"$mysql\"}[1m]))",
     "legendFormat": "Aborted Connects (attempts) on - {{ service }}"
    },
    {
     "expr": "sum by (service) (rate(mysql_global_status_aborted_clients{namespace=~\"$namespace\",service=~\"$mysql\"}[1m]))",
     "legendFormat": "Aborted Clients (timeout) on - {{ service }}"
    }
   ]
  }
 ]
}