{
 "title": "KubeDB / MySQL / Pod",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "mysql",
    "label": "MySQL",
    "query": {
     "query": "label_values(mysql_up{namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(mysql_up{namespace=~\"$namespace\", service=~\"$mysql\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Name",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_up{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MySQL Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_uptime{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_version_info{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(mysql_global_status_queries{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_max_used_connections{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Max Used Connects"
      },
      {
       "expr": "mysql_global_variables_max_connections{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Max Connects"
      }
     ]
    },
    {
     "title": "MySQL Aborted Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_aborted_connects{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Aborted Connects"
      },
      {
       "expr": "mysql_global_status_aborted_clients{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Aborted Clients"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_threads_connected{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Threads Connected"
      },
      {
       "expr": "mysql_global_status_threads_running{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Threads Running"
      }
     ]
    },
    {
     "title": "MySQL Thread Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_variables_thread_cache_size{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Thread Cache Size"
      },
      {
       "expr": "mysql_global_status_threads_cached{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Threads Cached"
      }
     ]
    }
   ]
  },
  {
   "title": "Select Types and Sorts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Select Types",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_select_full_join{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Select Full Join"
      },
      {
       "expr": "mysql_global_status_select_scan{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Select Scan"
      }
     ]
    },
    {
     "title": "MySQL Sorts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_sort_rows{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Sort Rows"
      },
      {
       "expr": "mysql_global_status_sort_range{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Sort Range"
      },
      {
       "expr": "mysql_global_status_sort_merge_passes{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Sort Merge Passes"
      },
      {
       "expr": "mysql_global_status_sort_scan{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Sort Scan"
      }
     ]
    }
   ]
  },
  {
   "title": "Temporary Objects & Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Temporary Objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_created_tmp_tables{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Created Tmp Tables"
      },
      {
       "expr": "mysql_global_status_created_tmp_disk_tables{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Created Tmp Disk Tables"
      },
      {
       "expr": "mysql_global_status_created_tmp_files{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Created Tmp Files"
      }
     ]
    },
    {
     "title": "MySQL Slow Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_slow_queries{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Slow Queries"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Locks and Questions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Table Locks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_table_locks_immediate{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Table Locks Immediate"
      },
      {
       "expr": "mysql_global_status_table_locks_waited{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Table Locks Waited"
      }
     ]
    },
    {
     "title": "MySQL Questions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_questions{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}",
       "legendFormat": "Questions"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "MySQL Network Usage Hourly",
     "type": "graph",
     "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service) (increase(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}[1h]))",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service) (increase(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$mysql\",pod=~\"$pod\"}[1h]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}