{
 "title": "KubeDB / Solr / Database",
 "description": "Solr Database Dashboard for Prometheus Solr Exporter",
 "tags": [
  "kubedb",
  "solr",
  "database"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(kubedb_com_solr_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(solr_ping{namespace=~\"$namespace\",service=~\"$app-stats\",zk_host=~\".+\"},zk_host)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\".+\"},base_url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Solr Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of total nodes",
   "type": "stat",
   "description": "Total nodes in the cluster",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (core) (count(count by (node_name) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\"})) < solr_collections_live_nodes{namespace=~\"$namespace\",service=~\"$app-stats\"} or solr_collections_live_nodes{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Live nodes",
   "type": "stat",
   "description": "Total number of live nodes",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (core) (count(count by (node_name) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\"})) < solr_collections_live_nodes{namespace=~\"$namespace\",service=~\"$app-stats\"} or solr_collections_live_nodes{namespace=~\"$namespace\",service=~\"$app-stats\"})"
    }
   ]
  },
  {
   "title": "Shard leaders",
   "type": "graph",
   "description": "All shard leaders.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Leaders" }
   ],
   "targets": [
    {
     "expr": "max by (core,replica, shard, collection) (solr_collections_shard_leader{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Number of Collections",
   "type": "stat",
   "description": "Total number of collections",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (collection)  (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\"}))"
    }
   ]
  },
  {
   "title": "Total Replicas",
   "type": "stat",
   "description": "Total number of replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (core) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}))"
    }
   ]
  },
  {
   "title": "Active Replicas",
   "type": "stat",
   "description": "Total number of active replicas",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (core) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",state=\"active\"})) OR on() vector(0)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Down Replicas",
   "type": "stat",
   "description": "Number of down replicas",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (core) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",state=\"down\"})) OR on() vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Recovering replicas",
   "type": "stat",
   "description": "Total number of recovering replicas",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (core) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",state=\"recovering\"})) OR on() vector(0)",
     "legendFormat": "Recovering"
    }
   ]
  },
  {
   "title": "Recovery failed replicas",
   "type": "stat",
   "description": "Total number of replicas failed to recover",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (core) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",state=\"recovery_failed\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Zookeeper Healthy Nodes",
   "type": "stat",
   "description": "Total number of zookeeper healthy nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(max by (host) (solr_zookeeper_nodestatus{namespace=~\"$namespace\",service=~\"$app-stats\"}) == 1))",
     "legendFormat": "Healthy Nodes"
    }
   ]
  },
  {
   "title": "Zookeeper ensemble size",
   "type": "stat",
   "description": "Size of zookeeper ensemble",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (zk_host) (solr_zookeeper_ensemble_size{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "Ensemble size"
    }
   ]
  },
  {
   "title": "Replica state history",
   "type": "graph",
   "description": "Current state of replicas. We are showing down replica here.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Non-active replicas" }
   ],
   "targets": [
    {
     "expr": "1 - max by (core, state) (solr_collections_replica_state{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",})",
     "legendFormat": "{{core}} = {{state}}"
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total QPS (by collection)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate  aggregated by collection, roughly the current QPS across all nodes per ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_query_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Total QPS (by node)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate aggregated by base_url (Solr node)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_query_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  { "title": "JVM Metics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Buffers",
   "type": "graph",
   "description": "Total number of jvm buffers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "description": "Size of buffer in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "description": "Total number of garbage collection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Time Seconds",
   "type": "graph",
   "description": "Total time of garbage collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "description": "Total heap size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Non-heap size",
   "type": "graph",
   "description": "Size of non heap memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_non_heap_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Pool size",
   "type": "graph",
   "description": "Pool size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_pools_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{space}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory size",
   "type": "graph",
   "description": "Memory size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Thread size",
   "type": "graph",
   "description": "Total thread size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_threads{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Request",
   "type": "graph",
   "description": "Total number of requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_requests_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "description": "Total request time in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_time_seconds_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "description": "Total number of node client errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_client_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "graph",
   "description": "Total number of client server errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_server_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Total node errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "graph",
   "description": "Total node timeout",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_timeouts_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "description": "Total node cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_cores{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Core Root File System",
   "type": "graph",
   "description": "Total memory consumed by core root file system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Thread pool completed",
   "type": "graph",
   "description": "Total thread pool completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_completed_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread pool submitted",
   "type": "graph",
   "description": "Total thread pool submitted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_submitted_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread pool running",
   "type": "graph",
   "description": "Total number of node thread pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_running{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Total number of node connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_connections{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{item}}"
    }
   ]
  },
  {
   "title": "Leader Count(by node)",
   "type": "graph",
   "description": "Total number of leaders by node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (base_url) (max by (core) (solr_collections_shard_leader{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\"}))",
     "legendFormat": "{{base_url}}"
    }
   ]
  }
 ]
}