{
 "title": "KubeDB / Solr / Pod",
 "description": "Solr Pod Dashboard for Prometheus Solr Exporter",
 "tags": [
  "kubedb",
  "solr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(kubedb_com_solr_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(solr_ping{namespace=\"$namespace\",service=~\"$app-stats\",zk_host=~\"$zk_host\",pod=~\".+\"},pod)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\".+\"},base_url)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(solr_collections_shard_state{namespace=\"$namespace\",service=~\"$app-stats\",zk_host=~\"$zk_host\",collection=~\".+\"},collection)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(solr_collections_shard_state{namespace=\"$namespace\",service=~\"$app-stats\",zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\".+\"},shard)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values(solr_collections_replica_state{namespace=\"$namespace\",service=~\"$app-stats\",zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_collections_replica_state{namespace=\"$namespace\",service=~\"$app-stats\",zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},core)"
    }
   },
   {
    "name": "searchHandler",
    "query": {
     "query": "label_values(solr_metrics_core_query_errors_1minRate{namespace=\"$namespace\",service=~\"$app-stats\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},searchHandler)"
    }
   },
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(solr_ping{namespace=~\"$namespace\",service=~\"$app-stats\",zk_host=~\".+\"},zk_host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total QPS(by collection)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate  aggregated by collection and pod, roughly the current QPS across all nodes per ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_query_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total QPS(by node)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate aggregated by base_url (Solr node) and pods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (base_url) (solr_metrics_core_query_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Distributed query time per core(p95 ms)",
   "type": "graph",
   "description": "Imp[lies distributed query time in 95ms.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p95_ms{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed Query Time per Core (p99 ms)",
   "type": "graph",
   "description": "Implies distributed query time per core in 99ms.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p99_ms{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Distributed QPS per core(5-min rate)",
   "type": "graph",
   "description": "Distributed QPS per core in 5min rate",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_5minRate{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}} {{pod}} {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed QPS per Core (1-min rate)",
   "type": "graph",
   "description": "Distributed QPS per core in 1 min rate",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{pod}} {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed Query Time per Core (p75 ms)",
   "type": "graph",
   "description": "Distributed query time per core in 75ms",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p75_ms{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}} {{pod}} {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Query Errors per Core (1-min rate)",
   "type": "graph",
   "description": "Implies query errors per core in 1 min rate.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_errors_1minRate{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}"
    }
   ]
  },
  { "title": "Jetty Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Impliess jetty requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_requests_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{method}} {{pod}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "description": "Implies jetty response.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_response_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{status}} {{pod}}"
    }
   ]
  },
  {
   "title": "Dispatches",
   "type": "graph",
   "description": "Implies query dispatches",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_dispatches_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{pod}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Buffers",
   "type": "graph",
   "description": "Implies jvm buffers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "description": "Implies jvm buffer size in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers_bytes{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{pool}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "description": "Implies garbage collection count.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Time Seconds",
   "type": "graph",
   "description": "Implies garbage collection time in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Non-Heap Size",
   "type": "graph",
   "description": "Implies non-heap size.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_non_heap_bytes{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "graph",
   "description": "Implies pool size.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_pools_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{space}} {{pod}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "description": "Implies memory size.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Implies number of threads",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_threads{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  { "title": "OS Metrics.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Memory Size",
   "type": "graph",
   "description": "Implies memory size of jvm os.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "Implies jvm os file descriptor.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "description": "Imples jvm os cpu load.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "description": "Implies jvm os cpu time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "Implies jvm os load average.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_load_average{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Implies total node request for solr.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_requests_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "description": "Implies total node request time in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_time_seconds_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "description": "Solr node client error.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_client_errors_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "description": "Solr node server error.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_server_errors_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "total node error in solr",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_errors_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "description": "total node timeouts.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_timeouts_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "description": "total node cores.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_cores{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Core Root File System",
   "type": "graph",
   "description": "memory occupied by core root fs in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Thread Pool Completed",
   "type": "graph",
   "description": "total thread pool completed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_completed_total{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}} {{pod}}"
    }
   ]
  },
  {
   "title": "Thread Pool Submitted",
   "type": "graph",
   "description": "Total thread pool submitted.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_submitted_total{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}} {{pod}}"
    }
   ]
  },
  {
   "title": "Thread Pool Running",
   "type": "graph",
   "description": "Total thread pool running.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_running{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}} {{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "solr node connections.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_connections{namespace=~\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}",
     "legendFormat": "{{base_url}} {{handler}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Leader Count (by node)",
   "type": "graph",
   "description": "Number of leaders on each node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (base_url) (max by (core) (solr_collections_shard_leader{namespace=\"$namespace\",service=~\"$app-stats\",base_url=~\"$base_url\",pod=~\"$pod\"}))",
     "legendFormat": "{{base_url}} {{pod}}"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Total core request.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "description": "Total core time in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "description": "Total core client error.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "total core errors",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "description": "Total core timeout.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}{{pod}}"
    }
   ]
  },
  {
   "title": "Searcher Cache Hit Ratio",
   "type": "graph",
   "description": "Core searcher cache hit ratio.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache_ratio{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "graph",
   "description": "Core searcher cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "graph",
   "description": "Core searcher warm up time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{pod}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "graph",
   "description": "Core searcher cumulative cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "description": "Core file system size in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "description": "Core index size in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds (cumulative)",
   "type": "graph",
   "description": "Cumulative core update handler.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "graph",
   "description": "Core update handler pending doc.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}{{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "graph",
   "description": "Number of core update handler delete by ID.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "description": "Number of core update handler deleted by query",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "graph",
   "description": "Total number of update handler expunge deletes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "description": "Total number of update handler merges.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "graph",
   "description": "Total number of update handler splits.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "graph",
   "description": "Total number of update handler rollbacks.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "graph",
   "description": "Total number of update handle optimizes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "graph",
   "description": "Total number of update handler auto commits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "graph",
   "description": "Total number of soft auto commits for update handler.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "description": "Total number of update handler commits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "graph",
   "description": "Total number of update handler error",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{pod}}"
    }
   ]
  }
 ]
}