{
 "title": "KubeDB / Cassandra / Pod",
 "description": "Monitoring for Cassandra clusters",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\"}, cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 0 },
   "options": {
    "content": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg\" width=\"150\" height=\"100\" style=\"background-color:white;/>\n<span style=\"font-family:verdana,geneva,sans-serif;\"><span style=\"font-size:28px;\"><span style=\"color:#ffffff;\">&nbsp;&nbsp;Cassandra cluster</span></span></span>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": { "content": "# Cluster operations" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster ops",
   "type": "timeseries",
   "description": "Total aggregated requests per second cluster-wise",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:casread:latency:oneminuterate\"})",
     "legendFormat": "CasRead"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:caswrite:latency:oneminuterate\"})",
     "legendFormat": "CasWrite"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:rangeslice:latency:oneminuterate\"})",
     "legendFormat": "RangeSlice"
    },
    {
     "expr": "sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:clientrequest:viewwrite:latency:oneminuterate\"})",
     "legendFormat": "ViewWrite"
    }
   ]
  },
  {
   "title": "Operations per instance",
   "type": "timeseries",
   "description": "Requests served by each instance of the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"}) by (instance), \"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": { "content": "# Reads and Writes" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read operations",
   "type": "timeseries",
   "description": "Read operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"}+0.00000001) by (instance),\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Write operations",
   "type": "timeseries",
   "description": "Write operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"}+0.00000001) by (instance),\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": { "content": "# Latencies" },
   "targets": [
    {}
   ]
  },
  {
   "title": "50th percentile read latency per instance",
   "type": "timeseries",
   "description": "50th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:50thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "75th percentile read latency per instance",
   "type": "timeseries",
   "description": "75th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:75thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "99th percentile read latency per instance",
   "type": "timeseries",
   "description": "99th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:99thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "75th percentile write latency per instance",
   "type": "timeseries",
   "description": "75th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:75thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "75th percentile write latency per instance",
   "type": "timeseries",
   "description": "75th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:75thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "99th percentile write latency per instance",
   "type": "timeseries",
   "description": "99th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:99thpercentile\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
   "options": { "content": "# Compactions and SSTables" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending and Running compactions",
   "type": "timeseries",
   "description": "Pending and Running compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",name=~\"org:apache:cassandra:metrics:compaction:pendingtasks:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_P"
    },
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",name=~\"org:apache:cassandra:metrics:threadpools:internal:compactionexecutor:activetasks:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_A"
    }
   ]
  },
  {
   "title": "Completed compactions",
   "type": "timeseries",
   "description": "Completed compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",name=~\"org:apache:cassandra:metrics:compaction:completedtasks:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Total completed compactions",
   "type": "timeseries",
   "description": "Total completed compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:compaction:totalcompactionscompleted:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Bytes compacted",
   "type": "timeseries",
   "description": "Bytes compacted per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:compaction:bytescompacted:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    },
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\", name=~\"org:apache:cassandra:metrics:table:dfce:documents:compactionbyteswritten:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_docs"
    }
   ]
  },
  {
   "title": "Live SSTables per instance",
   "type": "timeseries",
   "description": "Live SSTables per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:table:livesstablecount:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "SSTables per read histogram",
   "type": "timeseries",
   "description": "SSTables per read histogram percentiles",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",job=~\".+\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:50thpercentile\"})",
     "legendFormat": "p55"
    },
    {
     "expr": "avg(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",job=~\".+\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:75thpercentile\"})",
     "legendFormat": "p75"
    },
    {
     "expr": "avg(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",job=~\".+\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:99thpercentile\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".+\",job=~\".+\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:mean\"})",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 },
   "options": { "content": "# Cache" },
   "targets": [
    {}
   ]
  },
  {
   "title": "KeyCache one minute hit rate per instance",
   "type": "timeseries",
   "description": "KeyCache one minute hit rate per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:cache:keycache:oneminutehitrate:value\"}*100,\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "KeyCache size / entries per instance",
   "type": "timeseries",
   "description": "KeyCache size / entries per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:cache:keycache:size:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_sz"
    },
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:cache:keycache:entries:value\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_en"
    }
   ]
  },
  {
   "title": "KeyCache hits / requests per instance",
   "type": "timeseries",
   "description": "KeyCache hits / requests per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:cache:keycache:hits:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_hits"
    },
    {
     "expr": "label_replace(cassandra_stats{cluster=\"$cluster\",datacenter=~\".*\",pod=~\"$pod\",instance=~\".*\",name=~\"org:apache:cassandra:metrics:cache:keycache:requests:count\"},\"short_instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_instance}}_reqs"
    }
   ]
  }
 ]
}