{
 "title": "KubeDB / Kafka / Pod",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "Kafka",
    "query": {
     "query": "label_values(kubedb_com_kafka_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_replicationbytesout_total{namespace=~\"$namespace\",pod=~\"$app.+$\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Pod uptime",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Messages count",
   "type": "stat",
   "description": "Total messages in this pod",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Replica Manager Leader Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Offline Replica Count",
   "type": "stat",
   "description": "Number of offline replicas",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_offlinereplicacount{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Local items Request time",
   "type": "graph",
   "description": "time of of  the requested item processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems_count{namespace=\"$namespace\",pod=~\"$pod\"} != 0 ",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Local Items response time",
   "type": "graph",
   "description": "time of of  the response item processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems_count{namespace=\"$namespace\",pod=~\"$pod\"} != 0",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Network-I/O-rate",
   "type": "graph",
   "description": "The average number of network operations (reads or writes) on all connections per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_network_io_rate{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-{{ listener }}"
    }
   ]
  },
  {
   "title": "Failed Authentication Rate",
   "type": "graph",
   "description": "Connections per second that failed authentication.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_successful_authentication_rate{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-{{ listener }}"
    }
   ]
  },
  { "title": "JVM Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "description": "JVM threads info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM memory used [non-heap]",
   "type": "graph",
   "description": "used non-heap memory in Mi",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"nonheap\"} / 1024 / 1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM memory used [heap]",
   "type": "graph",
   "description": "used heap memory in Mi",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"} / 1024 / 1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM pool bytes used",
   "type": "graph",
   "description": "JVM pool usage info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\",pod=\"$pod\"} / 1024 / 1024",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "description": "GC count increase",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}-{{ gc }}"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "graph",
   "description": "GC time increase",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}-{{ gc }}"
    }
   ]
  },
  { "title": "CPU And memory Usage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) / count(container_cpu_usage_seconds_total{pod=~\"$pod\",container=~\"kafka\"}) * 100",
     "legendFormat": "CPU used (%)"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "graph",
   "description": "Kafka pod's used memory",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 48 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"}) / 1024 / 1024",
     "legendFormat": "used memory"
    }
   ]
  }
 ]
}