{
 "title": "KubeDB / Kafka / ConnectCluster / Pod",
 "description": "Kafka Connect dashboard for metrics exported by Prometheus Operator",
 "tags": [
  "kafka",
  "kubedb",
  "JMX exporter",
  "kafka-connect",
  "connectcluster",
  "connector"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "ConnectCluster",
    "query": {
     "query": "label_values(kafka_kubedb_com_connectcluster_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kafka_connect_app_info{namespace=~\"$namespace\",pod=~\"$app.+$\"},pod)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(kafka_connect_connector_status{namespace=~\"$namespace\",pod=~\"$pod\"},connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Pod uptime",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connector count",
   "type": "stat",
   "description": "Total connector in this cluster",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Task count",
   "type": "stat",
   "description": "Total tasks in pods",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Network-I/O Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_network_io_total{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network-I/O-rate",
   "type": "timeseries",
   "description": "The average number of network operations (reads or writes) on all connections per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Task Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_running_ratio{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Avg",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "JVM Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "JVM Threads used",
   "type": "timeseries",
   "description": "JVM threads info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-current"
    },
    {
     "expr": " jvm_threads_daemon{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-daemon"
    },
    {
     "expr": " jvm_threads_peak{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-peak"
    },
    {
     "expr": " jvm_threads_deadlocked{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}-deadlocked"
    }
   ]
  },
  {
   "title": "JVM memory used [non-heap]",
   "type": "timeseries",
   "description": "used non-heap memory in Mi",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"nonheap\"} / 1024 / 1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM memory used [heap]",
   "type": "timeseries",
   "description": "used heap memory in Mi",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"} / 1024 / 1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM pool bytes used",
   "type": "timeseries",
   "description": "JVM pool usage info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\"} / 1024 / 1024",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "description": "GC count increase",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}-{{ gc }}"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "timeseries",
   "description": "GC time increase",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}-{{ gc }}"
    }
   ]
  },
  { "title": "Source Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll Total",
   "type": "timeseries",
   "description": "The total records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_total{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write Total",
   "type": "timeseries",
   "description": "Total records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_total{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(connector, task) (kafka_connect_source_task_source_record_active_count{namespace=~\"$namespace\",pod=~\"$pod\", connector=~\"$connector\", task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(connector, task) (kafka_connect_source_task_source_record_active_count{namespace=~\"$namespace\",pod=~\"$pod\", connector=~\"$connector\", task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Sink Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Put Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_avg_time_ms{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_max_time_ms{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "table",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_partition_count{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Send Total",
   "type": "table",
   "description": "The total record send from kafka",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_sink_record_send_total{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Read Total",
   "type": "table",
   "description": "The total record read from kafka",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_sink_record_read_total{namespace=~\"$namespace\",pod=~\"$pod\", connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Task Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_failures{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce failures",
   "type": "timeseries",
   "description": "Number of produce failures to the dead letter queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_failures{namespace=~\"$namespace\",pod=~\"$pod\", connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_records_skipped{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_errors{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_errors_logged{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_retries{namespace=~\"$namespace\",pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}