{
 "title": "KubeDB / Kafka / ConnectCluster / Connect",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "ConnectCluster",
    "query": {
     "query": "label_values(kafka_kubedb_com_connectcluster_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ConnectCluster Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of Connect Cluster",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_kubedb_com_connectcluster_status_phase{namespace=\"$namespace\", app=\"$app\"} == 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Cluster Uptime",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=~\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Connector count",
   "type": "stat",
   "description": "Total connector in this cluster",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{namespace=~\"$namespace\", pod=~\"$app-.+$\"})"
    }
   ]
  },
  {
   "title": "Task count",
   "type": "stat",
   "description": "Total tasks in pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{namespace=~\"$namespace\", pod=~\"$app-.+$\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "description": "JVM version of the cluster",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\", pod=~\"$app-.+$\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Connect Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Connect Worker",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_app_info{instance=~\"$instance\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{instance=~\"$instance\",version!=\"\"}"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_connector_count{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_connector_startup_success_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker__connector_startup_failure_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_task_count{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_task_startup_success_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_task_startup_failure_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"})"
    }
   ]
  },
  { "title": "Connector Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{namespace=\"$namespace\",pod=~\"$app-.+$\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    },
    {
     "expr": "kafka_connect_connector_info{namespace=\"$namespace\",pod=~\"$app-.+$\",connector_type!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{namespace=\"$namespace\",pod=~\"$app-.+$\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{namespace=\"$namespace\",pod=~\"$app-.+$\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_total_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_running_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_failed_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_paused_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_destroyed_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_worker_connector_unassigned_task_count{namespace=\"$namespace\",pod=~\"$app-.+$\"})"
    }
   ]
  },
  { "title": "I/O Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average number of requests",
   "type": "timeseries",
   "description": "Average number of requests sent per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_connect_request_size_avg{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "graph",
   "description": "Fraction of time the I/O thread spent doing I/O",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_io_ratio{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Total",
   "type": "timeseries",
   "description": "Bytes read off all sockets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Total",
   "type": "timeseries",
   "description": "Average number of outgoing bytes sent to all servers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "timeseries",
   "description": "Current number of active connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_connection_count{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_response_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success authentication connections",
   "type": "timeseries",
   "description": "Connections that were successfully authenticated using SASL or SSL",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_successful_authentication_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "timeseries",
   "description": "Connections that failed authentication",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_failed_authentication_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network IO Total",
   "type": "timeseries",
   "description": "Total number of network operations (reads or writes) on all connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_network_io_total{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rebalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Rebalances average time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{namespace=~\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time since last rebalance ",
   "type": "graph",
   "description": "Time since last rebalance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{namespace=~\"$namespace\",pod=~\"$app-.+$\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}