{
 "title": "KubeDB / Singlestore / Pod",
 "tags": [
  "singlestore",
  "pod",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Singlestore",
    "query": {
     "query": "label_values(kubedb_com_singlestore_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(memsql_up{namespace=~\"$namespace\", service=~\"$app+-stats\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Singlestore Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_up{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_status_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_variable_memsql_version{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(memsql_status_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Buffer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_variable_transaction_buffer{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{pod=~\"$pod\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Singlestore Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_variable_max_connection_threads{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max Connection Threads - {{pod}}"
    },
    {
     "expr": "memsql_variable_max_connections{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max Connection - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_aborted_connects{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Aborted Connects - {{pod}}"
    },
    {
     "expr": "memsql_status_aborted_clients{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Aborted Clients - {{pod}}"
    }
   ]
  },
  { "title": "Client Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Singlestore Client Thread Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_threads_connected{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Connected - {{pod}}"
    },
    {
     "expr": "memsql_status_threads_running{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Running - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Thread Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_variable_thread_cache_size{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Thread Cache Size - {{pod}}"
    },
    {
     "expr": "memsql_status_threads_cached{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Cached - {{pod}}"
    },
    {
     "expr": "memsql_status_threads_created{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Created - {{pod}}"
    }
   ]
  },
  { "title": "Queries, Failed Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Singlestore Failed Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_failed_write_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "failed write queries -{{pod}}"
    },
    {
     "expr": "memsql_status_failed_read_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "failed read queries -{{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Queries - {{pod}}"
    }
   ]
  },
  {
   "title": "Total Disk Size MB, Memory Summary Variables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Singlestore Total Disk Size MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_disk_total_size_mb{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Total Disk Size MB - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Memory Summary Variables",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_status_total_server_memory{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Total Server Memory - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_table_memory{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Table Memory - {{pod}}"
    },
    {
     "expr": "memsql_status_buffer_manager_memory{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Buffer Manager Memory - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_query_execution{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Query Execution - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_variable{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc variable - {{pod}}"
    }
   ]
  },
  { "title": "Locks and Questions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Singlestore Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_row_lock_wait_time{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "row lock wait time - {{pod}}"
    },
    {
     "expr": "memsql_variable_lock_wait_timeout{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "variable lock wait timeout - {{pod}}"
    },
    {
     "expr": "memsql_variable_distributed_commit_lock_timeout{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "variable distributes commit lock timeout - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Questions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memsql_status_questions{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Questions - {{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Singlestore Network Traffic",
   "type": "graph",
   "description": "\n\nHere we can see how much network traffic is generated by Singlestore. Outbound is network traffic sent from Singlestore and Inbound is network traffic Singlestore has received.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(memsql_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Inbound - {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(memsql_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Outbound - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Network Usage Hourly",
   "type": "graph",
   "description": "\n\nHere we can see how much network traffic is generated by Singlestore. Outbound is network traffic sent from Singlestore and Inbound is network traffic Singlestore has received.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(memsql_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[1h])",
     "legendFormat": "Received - {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(memsql_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[1h])",
     "legendFormat": "Sent - {{pod}}"
    }
   ]
  },
  { "title": "Row Store, Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Singlestore Row store variables",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_status_alloc_skiplist_tower{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Skiplist Tower - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_table_primary{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Table Primary - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_deleted_version{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Delete Version - {{pod}}"
    },
    {
     "expr": "memsql_status_alloc_hash_buckets{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Alloc Hash Buckets - {{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Pipelines",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_variable_pipelines_max_concurrent{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max Concurrent - {{pod}}"
    },
    {
     "expr": "memsql_variable_pipelines_cdc_java_heap_size{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "CDC Java Heap Size - {{pod}}"
    },
    {
     "expr": "memsql_variable_pipelines_pooled_extractor_batches{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Pooled Extractor Batches- {{pod}}"
    },
    {
     "expr": "memsql_variable_pipelines_offsets_gc_skew_time_minutes{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Offsets GC skew Time Minutes - {{pod}}"
    }
   ]
  },
  { "title": "SSL Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Singlestore SSL Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memsql_status_ssl_session_cache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": " Session Cache Hit - {{pod}}"
    },
    {
     "expr": "memsql_status_ssl_session_cache_misses{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Session Cache Misses - {{pod}}"
    },
    {
     "expr": "memsql_status_ssl_session_cache_size{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Session Cache Size - {{pod}}"
    },
    {
     "expr": "memsql_status_ssl_session_cache_overflows{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Session Cache Overflows - {{pod}}"
    }
   ]
  },
  {
   "title": "Free IO Pool Memory, PlanCache Memory ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Singlestore Free IO Pool Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memsql_status_ssl_session_cache_overflows{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
       "legendFormat": "Query Cache Size - {{pod}}"
      }
     ]
    },
    {
     "title": "Plancache Memory Management",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memsql_variable_disk_plan_expiration_minutes{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
       "legendFormat": "Disk Plan Expiration Minutes - {{pod}}"
      },
      {
       "expr": "memsql_variable_enable_disk_plan_expiration{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
       "legendFormat": "Disk_plan_expiration - {{pod}}"
      },
      {
       "expr": "memsql_variable_plan_expiration_minutes{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
       "legendFormat": "Plan Expiration Minutes - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}