{
 "title": "KubeDB / Postgres / Summary",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "label": "postgres",
    "query": {
     "query": "query_result(kubedb_com_postgres_created{namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Postgresql Version",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_info{namespace=\"$namespace\", app=\"$app\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Database uptime",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kubedb_com_postgres_created{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Total Replicas",
   "type": "stat",
   "description": "Total replica count of the Postgres database",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_replicas{namespace=\"$namespace\",app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "description": "Represent database status",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_status_phase{namespace=\"$namespace\", app=\"$app\"} == 1\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Mode",
   "type": "stat",
   "description": "KubeDB Postgres Current SSL Mode",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_info{namespace=\"$namespace\", app=\"$app\"}",
     "legendFormat": "{{sslMode}}"
    }
   ]
  },
  {
   "title": "Deletion Policy",
   "type": "stat",
   "description": "KubeDB Postgres Resource deletionPolicy",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_info{namespace=\"$namespace\", app=\"$app\"}",
     "legendFormat": "{{deletionPolicy}}"
    }
   ]
  },
  {
   "title": "CPU Request (Core)",
   "type": "stat",
   "description": "Initial Requested CPU amount by Postgres Instance",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_resource_request_cpu{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "CPU Limit(core)",
   "type": "stat",
   "description": "CPU Limit in core by Postgres instance",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_resource_limit_cpu{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "description": "Initial Requested Memory amount by Postgres Instance",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_resource_request_memory{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "KubeDB Postgres Total Memory Limit",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_resource_limit_memory{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Storage Request",
   "type": "stat",
   "description": "Intial Storage Request by Postgres Instance when deploying",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_postgres_resource_request_storage{namespace=\"$namespace\", app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Maximum number of concurrent connections of the Postgres instance",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pg_settings_max_connections{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"})"
    }
   ]
  },
  {
   "title": "Primary Pod FailOver Indicator",
   "type": "graph",
   "description": "The current active line shows the current primary pod",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "AVG(rate(pg_stat_replication_reply_time{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connnections",
   "type": "graph",
   "description": "Postgres connections information in real time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Postgres Replication Lag",
   "type": "graph",
   "description": "Shows the replication lag with primary",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{namespace=\"$namespace\",application_name=~\"$app-\\\\d+$\"}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Raft Primary Tracker",
   "type": "timeseries",
   "description": "Track the current Primary for Raft",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_coordinator_raft_primary{namespace=\"$namespace\", pod=~\"$app-.\"}"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage by Postgres pods",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "description": "CPU Quote information in details",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage by Postgres pods",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",pod=~\"$app-\\\\d+$\",container!=\"\"}) by (pod)"
    }
   ]
  },
  { "title": "Storage Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Disk usage by Postgres pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_blkio_device_usage_total{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W Info",
   "type": "graph",
   "description": "System Disk Usage Information",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-write"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-read"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m]) + rate(container_fs_writes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\",pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\",pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  { "title": "Persistent Storage Insight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Allocated Storage",
   "type": "table",
   "description": "This panel describes allocated persistent storage in a table format\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "bargauge",
   "description": "This panel shows the persistent volume usage in percentage. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / on(persistentvolumeclaim) group_left(pod) (kubelet_volume_stats_capacity_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}) )* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage History",
   "type": "timeseries",
   "description": "This panel describes the persistent volume usage in a time series. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$app-\\\\d+$\",namespace=~\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$app-\\\\d+$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}