{
 "title": "KubeDB / Postgres / Summary",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "postgres",
    "label": "postgres",
    "query": {
     "query": "query_result(kubedb_postgres_created{namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "description": "Postgresql Version",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_info{namespace=\"$namespace\", postgres=\"$postgres\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Database uptime",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kubedb_postgres_created{namespace=\"$namespace\", postgres=\"$postgres\"}"
    }
   ]
  },
  {
   "title": "Total Replicas",
   "type": "stat",
   "description": "Total replica count of the Postgres database",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_replicas{namespace=\"$namespace\",postgres=\"$postgres\"}"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "description": "Represent database status",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_status_phase{namespace=\"$namespace\", postgres=\"$postgres\"} == 1\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_info{namespace=\"$namespace\", postgres=\"$postgres\"}",
     "legendFormat": "{{sslMode}}"
    }
   ]
  },
  {
   "title": "Termination Policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_info{namespace=\"$namespace\", postgres=\"$postgres\"}",
     "legendFormat": "{{terminationPolicy}}"
    }
   ]
  },
  {
   "title": "Primary Pod FailOver Indicator",
   "type": "timeseries",
   "description": "Primary Pod Fail over detector, the line shows the current primary pod and the value will be near 1 and it is set as a placeholder",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "AVG(rate(pg_stat_replication_reply_time{namespace=\"$namespace\", pod=~\"$postgres-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Initial CPU Request (Core)",
   "type": "stat",
   "description": "Initial Requested CPU amount by Postgres Instance",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_resource_request_cpu{namespace=\"$namespace\", postgres=\"$postgres\"}"
    }
   ]
  },
  {
   "title": "Initial Memory Request",
   "type": "stat",
   "description": "Initial Requested Memory amount by Postgres Instance",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_resource_request_memory{namespace=\"$namespace\", postgres=\"$postgres\"}"
    }
   ]
  },
  {
   "title": "Initial Storage Request",
   "type": "stat",
   "description": "Intial Storage Request by Postgres Instance when deploying",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_postgres_resource_request_storage{namespace=\"$namespace\", postgres=\"$postgres\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$postgres-.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$postgres-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage Info",
   "type": "timeseries",
   "description": "System Disk Usage Information",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "AVG(node_filesystem_avail_bytes{job=\"node-exporter\"}) by (device)",
     "legendFormat": "{{device}}-Available"
    },
    {
     "expr": "AVG(node_filesystem_size_bytes{job=\"node-exporter\"}) by (device) - AVG(node_filesystem_free_bytes{job=\"node-exporter\"}) by (device) ",
     "legendFormat": "{{device}}-Used"
    },
    {
     "expr": "AVG(node_filesystem_size_bytes{job=\"node-exporter\"}) by (device)",
     "legendFormat": "{{device}}-Total"
    }
   ]
  },
  {
   "title": "Bandwidth (Received & Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$postgres-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-received"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$postgres-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-transmitted"
    }
   ]
  }
 ]
}