{
 "title": "KubeDB / Ignite / Pod",
 "tags": [ "ignite" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(up, job)" } },
   { "name": "cacheName", "label": "cacheName", "query": { "query": "" } },
   { "name": "node", "label": "node", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg (up{namespace=~\"demo\", pod= \"$node\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hour ((ignite_uptime{namespace=\"demo\", pod= \"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Baseline Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (cluster_TotalBaselineNodes{pod= \"$node\"})"
    }
   ]
  },
  {
   "title": "Rebalance tasks in progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "threadPools_GridRebalanceExecutor_ActiveCount{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "History of node restarts",
   "type": "timeseries",
   "description": "Active baseline nodes count",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " avg (up{namespace=\"demo\", pod= \"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sys_memory_heap_max {pod= \"$node\"} - sys_memory_heap_used{pod= \"$node\"})*100 / sys_memory_heap_max{pod= \"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_CpuLoad{pod= \"$node\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (sys_CpuLoad{namespace=\"demo\", pod= \"$node\"}) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap memory used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_memory_heap_used{namespace=\"demo\", pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region memory usage  history (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffheapUsedSize{namespace=\"demo\", pod= \"$node\"} / 1024 / 1024 / 1024 ",
     "legendFormat": "{{pod}} allocated size"
    },
    {
     "expr": "io_dataregion_default_OffHeapSize{namespace=\"demo\", pod= \"$node\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}} Max size"
    }
   ]
  },
  { "title": "Data Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Data region size (GB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffHeapSize{pod= \"$node\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Data region off Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffHeapSize{pod= \"$node\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data region offheap used (GB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffheapUsedSize{pod= \"$node\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- Max Size",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_MaxSize{pod= \"$node\"} / 1024 / 1024 / 1024\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- No of PagesRead",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_PagesRead{pod= \"$node\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- No of PagesWritten",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_PagesWritten{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cache_${cacheName}_CacheHits {pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cache_${cacheName}_CacheHits{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Puts",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cache_${cacheName}_CachePuts{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cache_${cacheName}_CacheMisses{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "gauge",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_${cacheName}_CacheSize{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(cache_${cacheName}_CacheHits{pod= \"$node\"}) / clamp_min((cache_${cacheName}_CacheHits{pod= \"$node\"}) + (cache_${cacheName}_CacheMisses{pod= \"$node\"}), 1)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Moving partitions",
   "type": "stat",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheGroups_ignite_sys_cache_LocalNodeMovingPartitionsCount{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Owning partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheGroups_ignite_sys_cache_LocalNodeOwningPartitionsCount{pod= \"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}