{
 "title": "KubeDB / Ignite / Database",
 "tags": [ "ignite" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(up, job)" } },
   { "name": "app", "label": "app", "query": { "query": "" } },
   { "name": "cacheName", "label": "cacheName", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg (up{namespace=~\"demo\", pod=~\"$app-.+$\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hour ((ignite_uptime{namespace=\"demo\",pod=~\"$app-.+$\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Baseline Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (cluster_TotalBaselineNodes)"
    }
   ]
  },
  {
   "title": "Topology",
   "type": "stat",
   "description": "Topology snapshot",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"${job}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "History of node restarts",
   "type": "timeseries",
   "description": "Active baseline nodes count",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " avg (up{namespace=\"demo\", pod=~\"$app-.+$\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sys_memory_heap_max - sys_memory_heap_used)*100 / sys_memory_heap_max)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sys_CpuLoad * 100", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Rebalance tasks in progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "threadPools_GridRebalanceExecutor_ActiveCount",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (sys_CpuLoad{namespace=\"demo\", pod=~\"$app-.+$\"}) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap memory used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_memory_heap_used{namespace=\"demo\", pod=~\"$app-.+$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region memory usage  history (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffheapUsedSize{namespace=\"demo\", pod=~\"$app-.+$\"} / 1024 / 1024 / 1024 ",
     "legendFormat": "{{pod}} allocated size"
    },
    {
     "expr": "io_dataregion_default_OffHeapSize{namespace=\"demo\", pod=~\"$app-.+$\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}} Max size"
    }
   ]
  },
  { "title": "Data Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Data region size (GB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffHeapSize / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data region off Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffHeapSize / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data region offheap used (GB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_OffheapUsedSize / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- Max Size",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_MaxSize / 1024 / 1024 / 1024\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- No of PagesRead",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_PagesRead\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Region- No of PagesWritten",
   "type": "stat",
   "description": "< 70% is good",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dataregion_default_PagesWritten\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "cache_${cacheName}_CacheHits", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "cache_${cacheName}_CacheHits", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Cache Puts",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "cache_${cacheName}_CachePuts", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expr": "cache_${cacheName}_CacheMisses", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "gauge",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_${cacheName}_CacheSize", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(cache_${cacheName}_CacheHits) / clamp_min((cache_${cacheName}_CacheHits) + (cache_${cacheName}_CacheMisses), 1)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Moving partitions",
   "type": "stat",
   "description": "> 0 means that rebalance is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheGroups_ignite_sys_cache_LocalNodeMovingPartitionsCount ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Owning partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheGroups_ignite_sys_cache_LocalNodeOwningPartitionsCount",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}