{
 "title": "Stash / Dashboard",
 "description": "Grafana dashboard for Stash Enterprise edition",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
   },
   {
    "name": "target_kind",
    "label": "Target Kind",
    "query": "label_values(stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\"},target_kind)"
   },
   {
    "name": "target_name",
    "label": "Target Name",
    "query": "label_values(stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\"},target_name)"
   },
   {
    "name": "backup_invoker_kind",
    "query": "label_values(stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"},invoker_kind)"
   },
   {
    "name": "backup_invoker_name",
    "query": "label_values(stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"},invoker_name)"
   },
   {
    "name": "restore_invoker_kind",
    "query": "label_values(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"},invoker_kind)"
   },
   {
    "name": "restore_invoker_name",
    "query": "label_values(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"},invoker_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Applications",
   "type": "stat",
   "description": "Number of applications that has been configured for backup",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"})"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "stat",
   "description": "Total number of successful backup",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_backupsession_info{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Running Backups",
   "type": "stat",
   "description": "Number of backup sessions that are currently running",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_backupsession_info{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Skipped Backup",
   "type": "stat",
   "description": "Number of backup sessions that have been skipped",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_backupsession_info{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\", phase=\"Skipped\"})"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "description": "Number of backups that have failed",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_backupsession_info{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "stat",
   "description": "Total size of the backed up data",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stash_appscode_com_repository_size_bytes{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\",})"
    }
   ]
  },
  {
   "title": "Backup Targets",
   "type": "table",
   "description": "A list of backup targets",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "stash_appscode_com_backupconfiguration_info{namespace=~\"${namespace}\", target_kind=~\"${target_kind}\", target_name=~\"${target_name}\"}"
    },
    {
     "expr": "stash_appscode_com_backupconfiguration_conditions{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\", condition=\"CronJobCreated\", status=\"True\"}"
    },
    {
     "expr": "stash_appscode_com_backupsession_last_success_time_seconds{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"} * 1000"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage (Backup Job/Sidecar)",
   "type": "graph",
   "description": "CPU Usage by the backup pods",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"${namespace}\", container!=\"\", pod=~\"stash-backup-.*\",image!=\"\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"${namespace}\", container=\"stash\",image!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Backup Job/Sidecar)",
   "type": "graph",
   "description": "Memory usage by backup containers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", container!=\"\",pod=~\"stash-backup-.*\",image!=\"\"})by(pod) > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", container=\"stash\",image!=\"\"})by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Recent Backups",
   "type": "table",
   "description": "List of BackupSessions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "stash_appscode_com_backupsession_info{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_backupsession_duration_seconds{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_backupsession_created{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"} * 1000"
    }
   ]
  },
  { "title": "Repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Repositories",
   "type": "table",
   "description": "List of Repositories currently exist in the cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "stash_appscode_com_repository_integrity{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_repository_snapshot_count{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_repository_size_bytes{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_backupsession_last_success_time_seconds{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"} * 1000"
    }
   ]
  },
  {
   "title": "Repository Sizes",
   "type": "graph",
   "description": "Graph showing how repository size grows over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "stash_appscode_com_repository_size_bytes{namespace=~\"${namespace}\", invoker_kind=~\"${backup_invoker_kind}\", invoker_name=~\"${backup_invoker_name}\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "Restores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total Restore Count",
   "type": "stat",
   "description": "Number of total restore done within the time-frame",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\"})"
    }
   ]
  },
  {
   "title": "Successful Restores",
   "type": "stat",
   "description": "Total number of successful restores",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Running Restores",
   "type": "stat",
   "description": "Number of restore sessions that are currently running",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pending Restores",
   "type": "stat",
   "description": "Number of restore sessions that are currently pending to run",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\"}) - count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\", phase=~\"Succeeded|Failed|Running\"})"
    }
   ]
  },
  {
   "title": "Failed Restores",
   "type": "stat",
   "description": "Number of restore sessions that have failed",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Recent Restores",
   "type": "table",
   "description": "List of current RestoreSession in the cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "stash_appscode_com_restoresession_info{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_restoresession_duration_seconds{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\"}"
    },
    {
     "expr": "stash_appscode_com_restoresession_created{namespace=~\"${namespace}\", invoker_kind=~\"${restore_invoker_kind}\", invoker_name=~\"${restore_invoker_name}\"} * 1000"
    }
   ]
  },
  {
   "title": "CPU Usage (Restore Job/Sidecar)",
   "type": "graph",
   "description": "CPU Usage by the  restore pods",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"${namespace}\", container!=\"\", pod=~\"stash-restore-.*\",image!=\"\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"${namespace}\",container=\"stash-init\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Restore Job/Sidecar)",
   "type": "graph",
   "description": "Memory usage by  restore containers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"${namespace}\", container!=\"\",pod=~\"stash-restore-.*\",image!=\"\"})by(pod) > 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"${namespace}\", container=\"stash-init\",image!=\"\"})by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Operator & Pushgateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=~\"operator|pushgateway\", pod=~\".*stash-enterprise.*\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage of Stash Operator",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"operator|pushgateway\", pod=~\".*stash-enterprise.*\"})by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}