{
 "title": "KubeDB / Redis / Shard",
 "tags": [
  "redis",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "app",
    "label": "redis",
    "query": {
     "query": "query_result(kubedb_com_redis_created{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\",pod=~\"${app}-shard.*\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Shard Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Shard slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cluster_slots_ok{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Cluster nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cluster_known_nodes{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connected Slaves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slaves{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "My Slaves",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redis_connected_slave_offset_bytes{pod=~\"$pod\"} "
    }
   ]
  },
  {
   "title": "Cluster Shard slots Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cluster_slots_fail{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{pod=~\"$pod\"}",
     "legendFormat": "{{redis_mode}}"
    }
   ]
  },
  {
   "title": "Cluster Masters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cluster_size{pod=~\"$pod\"}"
    }
   ]
  }
 ]
}